/** Pure action rendering and transport-scope tests; not native browser evidence. */
import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {actionForm,actionEditForm,actionDetail,actionsPage} from '../web/dist/views-analysis.js';
import {state} from '../web/dist/state.js';
import {invalidateView} from '../web/dist/api.js';
const row=()=>({id:'a',version:3,payload:{title:'<script>标题</script>',owner:'原负责人',due_at:'2026-10-08',priority:'high',company:'测试企业',dataset_id:'d',identity_id:'i',run_id:'r',source_key:'s',description:'背景',acceptance:'人工核对并保存原始记录',status:'in_progress',history:[{at:'2026-09-30',to:'open',note:'助手确认创建',evidence_ids:[]}],changes:[{at:'2026-09-30',version:3,note:'重新分派任务',fields:{owner:{before:'旧负责人',after:'原负责人'}}}],origin:{owner:'旧负责人'}}});
function reset(){state.identities=[{id:'i',payload:{name:'测试身份'}}];state.identity='i';state.active='d';state.user={name:'测试用户'};state.datasets=[{id:'d',payload:{company:'测试企业'}}];}
test('manual action form binds identity and dataset at form creation',()=>{reset();const html=actionForm();assert(html.includes('data-identity-id="i"'));assert(html.includes('data-dataset-id="d"'));});
test('edit form shows existing assignment and deadline with exact optimistic version',()=>{reset();const html=actionEditForm(row());for(const value of ['data-version="3"','原负责人','2026-10-08','name="note"','name="acceptance"','name="priority"'])assert(html.includes(value));assert(!html.includes('<script>'));assert(!html.includes('name="identity_id"'));assert(!html.includes('name="source_key"'));});
test('action details render current context, legacy history and safe evidence choices',()=>{reset();const docs=[{id:'e',payload:{title:'可选原文'},eligible:true,review:{company:'测试企业',status:'accepted'}},{id:'other',payload:{title:'其他企业原文'},eligible:true,review:{company:'其他企业',status:'accepted'}},{id:'expired',payload:{title:'过期资料'},eligible:false,review:{company:'测试企业'}}];const html=actionDetail(row(),docs);for(const value of ['原负责人','2026-10-08','测试身份','旧负责人','重新分派任务','助手确认创建','可选原文','name="evidence_ids"','type="checkbox"','编辑行动'])assert(html.includes(value));assert(!html.includes('其他企业原文'));assert(!html.includes('过期资料'));assert(!html.includes('<script>'));});
test('accepted action requires reopening before editing',()=>{reset();const a=row();a.payload.status='done';const html=actionDetail(a);assert(!html.includes('data-action="action-edit"'));assert(html.includes('重新打开'));});
test('action page filters current identity and dataset instead of mixing work contexts',async()=>{reset();invalidateView();const old=globalThis.fetch;globalThis.fetch=async()=>new Response(JSON.stringify({items:[row(),{...row(),id:'b',payload:{...row().payload,title:'另一身份秘密任务',identity_id:'j'}},{...row(),id:'c',payload:{...row().payload,title:'另一企业任务',dataset_id:'else'}}]}),{headers:{'Content-Type':'application/json'}});try{const html=await actionsPage();assert(html.includes('测试企业'));assert(!html.includes('另一身份秘密任务'));assert(!html.includes('另一企业任务'));assert.deepEqual(state.cache.actions.map(a=>a.id),['a']);}finally{globalThis.fetch=old;}});
test('action handlers submit versioned edits and guard late evidence reads',()=>{const source=readFileSync(new URL('../web/app.ts',import.meta.url),'utf8');assert.match(source,/case 'action-edit-form':\{const saved=await workspace\('\/actions\/'\+form\.dataset\.id,'PUT',\{version:Number\(form\.dataset\.version\)/);assert(source.includes("if(submittedContext()&&form.isConnected)form.dataset.version=String(saved.version)"));assert(source.includes("const docs=await workspace('/evidence');if(!valid())break;inspect('行动与验收'"));assert(source.includes("evidence_ids:list('evidence_ids')"));assert(source.includes("'archive-dialog','action-detail'].includes"));assert(source.includes("case 'action-edit':{if(!safeToLeave())break;"));});
