import {formSnapshot} from './form-snapshot.js';
import {displayedComparisonMembers,comparisonPreviewDraft,comparisonSaveForm,comparisonCreateRequest,selectedComparisonRequest,syncComparisonControls,comparisonRemovalTarget,comparisonDeleteForm,removeSavedComparison,refreshComparisonReferences} from './saved-comparisons.js';
import {syncExperimentControls,selectedExperimentRequest,unchangedInputGuard} from './saved-experiments.js';
import {formSource,continueInsightDraft} from './business-source.js';
import {workflowGuide} from './workflow.js';
import {invalidateInteractions,interactionGuard,finishMutation,renewSavedDraft} from './interactions.js';
import {loadLayout,applyLayout,toggleNav,toggleAssistant,clearLayout,closeDrawers} from './layout.js';
import {copilotShell,copilotPage,mountCopilot,sendCopilot,resetCopilot,forgetCopilotComparison} from './copilot-ui.js';
import {servicesPage,trackingPage} from './views-services.js';
import {setupExperience,restoreIdentity} from './experience.js';
import {showBrandIntro,restoreMotion,motionSetting} from './brand.js';
import {evolutionPage,strategyForm,assessmentForm,graphCanvas,runtimeRibbon} from './views-orchestrator.js';
import {RunLive} from './live.js';
import {api,workspace,setCsrf,invalidateContext,contextGuard,invalidateView,ApiError,type Json} from './api.js';
import {state,routes,activeDataset,activeIdentity,scopedDatasets,roleNames} from './state.js';
import {esc,icon,button,routeButton,notice,empty,heading,field,input,textarea,select,formFooter,jsonView,table,timeText,pct,num,badge,status,citationCard,metricNames,metricValue} from './components.js';
import {briefPage,settingsPage,opsPage} from './pages.js';
import {revisionHistory,dataPage,datasetEditor,periodRow,financialFields,importForm,stageView,qualityPanel,evidencePage,evidenceForm,reviewEvidenceForm,evidenceScope,evidenceMetadataForm,memoryPage,memoryForm} from './views-data.js';
import {agentsPage,runPage,templateForm,rulesView} from './views-studio.js';
import {labPage,comparePage,comparisonOutput,reportsPage,reportCompareForm,reportSelectionDetails,reportComparisonView,actionsPage,actionForm,actionDetail,actionEditForm} from './views-analysis.js';
const root=document.querySelector<HTMLDivElement>('#app')!;
const modal=document.querySelector<HTMLDialogElement>('#modal')!;
const inspector=document.querySelector<HTMLDialogElement>('#inspector')!;
let live:RunLive|null=null;let renderEpoch=0;let signingUp=false;let currentHash='';let polling=false;let syncing=false;let syncPending=false;
const split=(v:string)=>v.split(/[,，\n]/).map(x=>x.trim()).filter(Boolean);
function toast(message:string,error=false){const host=document.querySelector('#notifications')!;for(const n of [...host.children])if(n.textContent===message)n.remove();while(host.children.length>=2)host.firstElementChild?.remove();const e=document.createElement('div');e.className='toast'+(error?' error':'');e.textContent=message;host.append(e);setTimeout(()=>e.remove(),error?10000:4000);}
function theme(){const t=state.user?.preferences.theme??'light';document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t;}
function dialog(title:string,body:string,wide=false){invalidateInteractions();modal.classList.toggle('wide',wide);modal.innerHTML=`<div class="dialog-head"><h2 id="modal-title">${esc(title)}</h2>${button(icon('close'),'close-modal','icon-button','aria-label="关闭窗口"')}</div><div class="dialog-body">${body}</div>`;if(!modal.open)modal.showModal();}
function inspect(title:string,body:string){invalidateInteractions();inspector.innerHTML=`<div class="dialog-head"><h2 id="inspector-title">${esc(title)}</h2>${button(icon('close'),'close-inspector','icon-button','aria-label="关闭详情"')}</div><div class="dialog-body">${body}</div>`;if(!inspector.open)inspector.showModal();}
function download(name:string,data:Json){const b=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const u=URL.createObjectURL(b);const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),5000);}
function safeToLeave(){return !state.dirty||window.confirm('当前输入尚未保存。离开后这些修改将丢失，是否继续？');}
function navigate(path:string,force=false){if(!force&&!safeToLeave())return;invalidateInteractions();closeDrawers();state.dirty=false;if(modal.open)modal.close();if(inspector.open)inspector.close();if(location.hash.slice(1)===path){void render();return;}location.hash=path;}
// Used after an explicit handoff confirmation: one history entry and one render.
async function navigateRendered(path:string){
 invalidateInteractions();closeDrawers();state.dirty=false;if(modal.open)modal.close();if(inspector.open)inspector.close();
 if(location.hash.slice(1)!==path)history.pushState(null,'','#'+path);
 const sameContext=contextGuard(),pending=render(),current=interactionGuard();
 const valid=()=>sameContext()&&current()&&document.querySelector<HTMLElement>('#main')?.dataset.page===path.split(':')[0];
 await pending;return valid()?valid:null;
}

function auth(){live?.dispose();live=null;renderEpoch++;root.innerHTML=`<main class="auth-page"><section class="auth-intro"><a class="brand" href="#"><img src="/assets/brand/logo.png" alt="">锂电智诊</a><div><span class="eyebrow">企业研究与经营诊断</span><h1>让每一个判断，<br>有据可循。</h1><p>连接经营数据、原始证据与协作分析。<br>从可核验的输入，走向可执行的行动。</p><div class="auth-principles"><span>${icon('database')} 数据有来源</span><span>${icon('network')} 执行可追溯</span><span>${icon('lock')} 授权有边界</span></div></div><small>你的数据仅在账户工作区内使用；外部模型按次授权。</small></section><section class="auth-panel"><div class="auth-box"><span class="eyebrow">${signingUp?'建立独立工作区':'进入你的工作区'}</span><h2>${signingUp?'创建账户':'欢迎回来'}</h2><form id="auth-form" class="stack">${field('邮箱',input('email','','type="email" autocomplete="username" required maxlength="180"'))}${field('密码',input('password','','type="password" autocomplete="'+(signingUp?'new-password':'current-password')+'" minlength="'+(signingUp?12:1)+'" maxlength="128" required'),signingUp?'至少 12 个字符，建议使用独立长密码':'')}${signingUp?field('称呼',input('name','','autocomplete="nickname" required maxlength="200"'))+field('工作视角',select('role',roleNames))+field('邀请码（部署方启用时填写）',input('invitation','','autocomplete="off"')):''}${formFooter(signingUp?'创建工作区':'登录')}</form><div class="auth-switch">${button(signingUp?'已有账户，返回登录':'没有账户？创建独立工作区','auth-toggle','text-button')}</div></div></section></main>`;}
function assistantShell(){return state.route==='copilot'?'':copilotShell();}
function shell(){theme();loadLayout(state.user.id);let section='';root.innerHTML=`<div class="workspace-shell"><aside class="sidebar" id="sidebar"><a class="brand" href="#brief"><img src="/assets/brand/logo.png" alt=""><span class="brand-word">锂电智诊</span></a>${button(icon('close'),'close-menu','icon-button menu-close','aria-label="收起导航"')}<button class="command-button" data-action="command">${icon('search')}<span>快速前往</span><kbd>Ctrl K</kbd></button><nav aria-label="主导航">${Object.entries(routes).map(([id,r])=>{const h=r.section!==section?`<div class="nav-section">${esc(r.section)}</div>`:'';section=r.section;return h+`<button data-route="${id}" title="${esc(r.label)}" aria-label="${esc(r.label)}" class="nav-item ${state.route===id?'active':''}" ${state.route===id?'aria-current="page"':''}>${icon(r.icon)}<span>${r.label}</span></button>`;}).join('')}</nav><label class="sidebar-role"><span>当前工作视角</span><select id="role-switch" aria-label="切换工作视角">${Object.entries(roleNames).map(([key,label])=>`<option value="${key}" ${state.user.preferences.role===key?'selected':''}>${esc(label)}</option>`).join('')}</select></label><div class="sidebar-footer"><span class="avatar">${esc(state.user.name.slice(0,1))}</span><div><strong>${esc(state.user.name)}</strong><small>${esc(activeIdentity()?.payload.name??'默认工作身份')}</small></div>${button(icon('logout'),'logout','icon-button','aria-label="退出登录"')}</div></aside><div class="main-shell"><header class="topbar"><div class="topbar-start">${button(icon('menu'),'menu','icon-button menu-button','aria-label="展开导航"')}<span class="breadcrumb">工作空间 <span>/</span> <strong>${esc(routes[state.route]?.label??'工作简报')}</strong></span></div><div class="topbar-controls"><label class="identity-select"><span class="sr-only">当前服务身份</span>${icon('memory')}<select id="active-identity"><option value="">默认身份</option>${state.identities.map(i=>`<option value="${esc(i.id)}" ${state.identity===i.id?'selected':''}>${esc(i.payload.name)}</option>`).join('')}</select></label><label class="company-select"><span class="sr-only">当前企业数据集</span>${icon('database')}<select id="active-dataset"><option value="">${state.datasets.length?'所有企业 / 未选择':'尚未添加企业'}</option>${scopedDatasets().map(d=>`<option value="${esc(d.id)}" ${state.active===d.id?'selected':''}>${esc(d.payload.company)} · ${esc(d.payload.name)}</option>`).join('')}</select></label>${button(icon('spark'),'show-assistant','icon-button','aria-label="打开研究助手"')}</div></header><div id="sync-notice" hidden></div><main id="main" tabindex="-1"><div class="loading" role="status"><span class="spinner"></span> 正在读取工作区…</div></main></div>${assistantShell()}<button type="button" id="drawer-backdrop" class="drawer-backdrop" aria-label="关闭抽屉" hidden></button></div>`;applyLayout();}
async function bootstrap(){const me=await api('/auth/me');setCsrf(me.csrf);state.user=me.user;const [ds,caps,ids]=await Promise.all([api('/datasets'),api('/capabilities'),api('/services/identities')]);state.datasets=ds.items;state.caps=caps;state.identities=ids.items;restoreIdentity();state.cursor=(await api('/sync?head=true')).cursor;syncPending=false;if(state.active&&!ds.items.some((d:Json)=>d.id===state.active))state.active='';if(state.active&&!scopedDatasets().some(d=>d.id===state.active))state.active='';if(!state.active&&scopedDatasets().length===1)state.active=scopedDatasets()[0].id;}
async function refreshData(valid:()=>boolean=()=>true){const [ds,caps,ids,me]=await Promise.all([api('/datasets'),api('/capabilities'),api('/services/identities'),api('/auth/me')]);if(!valid())return false;state.datasets=ds.items;state.caps=caps;state.identities=ids.items;if(state.identity&&!ids.items.some((x:Json)=>x.id===state.identity))state.identity='';state.user=me.user;setCsrf(me.csrf);if(state.active&&!scopedDatasets().some(d=>d.id===state.active))state.active='';return true;}
async function render(){invalidateInteractions();invalidateView();live?.dispose();live=null;if(!state.user)return auth();const seq=++renderEpoch;const [r,...rest]=(location.hash.slice(1)||'brief').split(':');state.route=r in routes?r:'brief';state.id=rest.join(':');currentHash=location.hash;shell();showSyncNotice();const main=document.querySelector('#main')!;try{const views:Record<string,()=>Promise<string>>={brief:briefPage,copilot:copilotPage,services:servicesPage,tracking:trackingPage,agents:()=>agentsPage(state.id),data:dataPage,evidence:evidencePage,lab:()=>labPage(state.id),compare:()=>comparePage(state.id),reports:reportsPage,actions:actionsPage,memory:memoryPage,ops:opsPage,settings:settingsPage,evolution:evolutionPage};const html=await views[state.route]();if(seq!==renderEpoch)return;main.innerHTML=workflowGuide(state.route)+html;syncExperimentControls(main,state.cache.planExperiments??[],scopedDatasets());syncComparisonControls(main,state.cache.planComparisons??[],scopedDatasets(),state.identity);(main as HTMLElement).dataset.page=state.route;applyLayout();void mountCopilot().catch(()=>{});document.title=routes[state.route].label+' · 锂电智诊';main.querySelector<HTMLHeadingElement>('h1')?.setAttribute('tabindex','-1');setupLive();if(state.route==='settings')main.insertAdjacentHTML('beforeend',appearancePanel());}catch(e){if(seq!==renderEpoch)return;if(e instanceof ApiError&&e.status===401){resetAuth();return;}main.innerHTML=heading('读取未完成','没有使用缓存或模拟数据替代失败的结果。')+notice(e instanceof Error?e.message:'读取失败','danger')+button('重新读取','refresh','primary');}}
function resetAuth(){invalidateInteractions();resetCopilot();clearLayout();state.identity='';state.identities=[];live?.dispose();live=null;state.user=null;state.cache={};state.cursor=0;syncPending=false;state.datasets=[];state.active='';state.query='';state.dirty=false;setCsrf('');if(modal.open)modal.close();if(inspector.open)inspector.close();modal.replaceChildren();inspector.replaceChildren();document.querySelector('#notifications')!.replaceChildren();auth();}
function read(form:HTMLFormElement){const f=new FormData(form);const str=(k:string)=>String(f.get(k)??'').trim();const val=(k:string,optional=false)=>{const s=str(k);if(optional&&!s)return null;const n=Number(s);if(!s||!Number.isFinite(n))throw new Error('请填写有效数值：'+k);return n;};return {f,str,val,check:(k:string)=>f.has(k),list:(k:string)=>f.getAll(k).map(String)};}
async function showStage(stage:Json){state.cache.stage=stage;dialog('保存前核对',stageView(stage),true);}
function rawDataset(d:Json){const p={...d};delete p.verification;delete p.input_amount_unit;return p;}
async function createEvidence(data:Json,company:string,global_scope=false){if(!company&&!global_scope)throw new Error('请填写所属企业，或明确选择通用资料。');const result=await api('/evidence','POST',{...data,company,global_scope});if(result.deduplicated)toast(result.notice,true);return result;}
async function ask(query:string){await sendCopilot(query);}
// All writes share a visible error boundary. Network failures are never automatically retried.
document.addEventListener('submit',async(event)=>{const form=event.target as HTMLFormElement;if(!(form instanceof HTMLFormElement))return;event.preventDefault();if(form.dataset.saved==='true'){toast('此表单已保存，请先核对并刷新后再编辑。',true);return;}if(form.dataset.submitting==='true')return;if(!form.reportValidity())return;const submit=form.querySelector<HTMLButtonElement>('button[type="submit"],button:not([type])');const error=form.querySelector('.form-error');if(error)error.textContent='';form.dataset.submitting='true';if(submit)submit.disabled=true;const submittedContext=contextGuard();const submittedCurrent=unchangedInputGuard(interactionGuard(),()=>form.isConnected?formSnapshot(form):null);
 try{const {f,str,val,check,list}=read(form);let changed=false,savedDraftMessage='';
 switch(form.id){
 case 'strategy-form':await workspace('/strategies','POST',{name:str('name'),depth:str('depth'),require_counterevidence:check('require_counterevidence'),require_gap_analysis:check('require_gap_analysis'),note:str('note')});changed=true;break;
 case 'assessment-form':await workspace('/runs/'+state.cache.run.id+'/assessment','POST',{review_context_hash:form.dataset.reviewContextHash??null,version:Number(form.dataset.version),verdict:str('verdict'),note:str('note'),expected_capabilities:list('expected_capabilities'),consent_replay:check('consent_replay')});changed=true;break;
 case 'appearance-form':motionSetting(str('motion'));toast('已应用动效偏好');state.dirty=false;break;
 case 'auth-form':{const r=await api('/auth/'+(signingUp?'register':'login'),'POST',signingUp?{email:str('email'),password:str('password'),name:str('name'),role:str('role'),invitation:str('invitation')}:{email:str('email'),password:str('password')});state.user=r.user;setCsrf(r.csrf);await bootstrap();state.dirty=false;await render();break;}
 case 'dataset-editor':{const periods=[...form.querySelectorAll<HTMLElement>('[data-period-row]')].map(row=>{const p:Json={period:row.querySelector<HTMLInputElement>('[name="period"]')!.value.trim()};for(const [k]of financialFields){const v=row.querySelector<HTMLInputElement>(`[name="${k}"]`)!.value;p[k]=v===''?null:Number(v);if(v!==''&&!Number.isFinite(p[k]))throw new Error('不能填写非有限数值');}return p;});if(!periods.length)throw new Error('至少需要一个季度');const data={company:str('company'),name:str('name'),amount_unit:str('amount_unit'),source_kind:'user_provided',source_url:str('source_url'),notes:str('notes'),periods};state.cache.editorDraft={id:form.dataset.id,payload:data,version:Number(form.dataset.version),basis:str('basis')};const req:Json={dataset:data,basis:str('basis')};if(form.dataset.id){req.target_id=form.dataset.id;req.target_version=Number(form.dataset.version);}const preview=await workspace('/imports/preview','POST',req);if(submittedCurrent())await showStage(preview);break;}
 case 'import-file-form':{const target=state.datasets.find(d=>d.id===str('target_id'));if(str('target_id')&&!target)throw new Error('目标数据集已不可用，请刷新后重试');const versions=JSON.parse(form.dataset.targetVersions??'{}');if(target&&!versions[target.id])throw new Error('目标版本缺失，请重新打开导入窗口');const originalMergeMode=str('merge_mode');f.set('target_version',String(target?versions[target.id]:0));if(!target)f.set('merge_mode','replace');state.cache.editorDraft=null;state.cache.importDraft={identity_id:state.identity,active_dataset:state.active,company:str('company'),amount_unit:str('amount_unit'),basis:str('basis'),target_id:str('target_id'),merge_mode:originalMergeMode,target_versions:versions};const preview=await workspace('/imports/file','POST',f);if(submittedCurrent())await showStage(preview);break;}
 case 'evidence-form':await createEvidence({title:str('title'),source_url:str('source_url'),published_at:str('published_at')||null,text:str('text')},str('company'),check('global_scope'));changed=true;break;
 case 'evidence-metadata-form':{const saved=await api('/evidence/'+form.dataset.id+'/metadata','PUT',{title:str('title'),source_url:str('source_url'),published_at:str('published_at')||null,version:Number(form.dataset.version)});if(submittedContext()&&form.isConnected)form.dataset.version=String(saved.version);changed=true;break;}
 case 'search-evidence-form':{const r=state.cache.searchCapture;await createEvidence({title:r.title,source_url:r.source_url,text:r.text,published_at:null,search_receipt:r.search_receipt,retrieved_at:r.retrieved_at},str('company'),check('global_scope'));changed=true;break;}
 case 'evidence-review-form':{const saved=await workspace('/evidence/'+form.dataset.id+'/review','PUT',{version:Number(form.dataset.version),company:str('company'),global_scope:check('global_scope'),expires_at:str('expires_at')||null,status:str('status'),stance:str('stance'),tags:split(str('tags')),note:str('note')});if(submittedContext()&&form.isConnected)form.dataset.version=String(saved.version);changed=true;break;}
 case 'evidence-search':{const r=await workspace('/retrieval?q='+encodeURIComponent(str('q'))+'&company='+encodeURIComponent(activeDataset()?.payload.company??''));if(!submittedCurrent())break;document.querySelector('#evidence-search-results')!.innerHTML=`<section class="panel"><div class="section-heading row-between"><h2>原文检索结果</h2>${badge(r.items.length+' 条')}</div>${r.items.map(citationCard).join('')||notice('当前企业作用域内没有匹配的有效资料。')}</section>`;break;}
 case 'document-form':{if(!str('company')&&!check('global_scope'))throw new Error('请填写所属企业，或明确选择通用资料。');const r=await api('/evidence/import','POST',f);toast(r.notice??'文档已保存，请审阅企业范围与适用边界。',!!r.deduplicated);changed=true;break;}
 case 'fetch-evidence-form':{if(!str('company')&&!check('global_scope'))throw new Error('请填写所属企业，或明确选择通用资料。');const r=await api('/evidence/fetch','POST',{url:str('url'),title:str('title'),published_at:str('published_at')||null,company:str('company'),global_scope:check('global_scope')});if(r.deduplicated)toast(r.notice,true);}changed=true;break;
 case 'public-search-form':{const r=await api('/research/search','POST',{query:str('query'),consent:check('consent')});if(!submittedCurrent())break;state.cache.search=r;document.querySelector('#public-search-results')!.innerHTML=(r.items??[]).map((v:Json,i:number)=>`<article class="citation"><h3>${esc(v.title)}</h3><p>${esc(v.text??'')}</p><p class="micro">${esc(v.source_url)}</p>${button('确认保存此摘要','save-search-result','secondary',`data-index="${i}"`)}</article>`).join('')||notice('没有通过过滤的结果。');break;}
 case 'memory-form':{const old=state.cache.memories?.find((m:Json)=>m.id===form.dataset.id);const payload={identity_id:old?.payload.identity_id??state.identity,text:str('text'),kind:str('kind'),company:str('company'),role:str('role'),expires_at:str('expires_at')||null,approved:check('approved'),source:'user'};if(form.dataset.id){const saved=await api('/memories/'+form.dataset.id,'PUT',{...payload,version:Number(form.dataset.version)});if(submittedContext()&&form.isConnected)form.dataset.version=String(saved.version);}else await api('/memories','POST',payload);changed=true;break;}
 case 'plan-form':{const sameContext=contextGuard();const current=unchangedInputGuard(interactionGuard(),()=>form.isConnected?JSON.stringify([...new FormData(form)]):null);const execution:Json={depth:str('depth')||null,parallelism:val('parallelism'),model_planning:check('model_planning')&&check('use_llm'),local_recovery:check('local_recovery'),max_revisions:val('max_revisions'),total_context_chars:val('total_context_chars'),forecast:check('forecast'),forecast_metric:str('forecast_metric')||'revenue',horizon:Number(str('forecast_horizon')||2),role_providers:Object.fromEntries(['analyst','researcher','challenger','planner','revision'].map(k=>[k,str('route_'+k)]).filter(([,v])=>v)),fallback_providers:str('fallback_provider')?[str('fallback_provider')]:[]};if(check('with_scenario')){if(str('scenario_note').length<5)throw new Error('启用情景需说明至少5个字符的假设依据');execution.scenario={price_change:Number(val('scenario_price'))/100,cost_change:Number(val('scenario_cost'))/100,volume_change:Number(val('scenario_volume'))/100,fixed_cost_share:Number(val('scenario_fixed'))/100,note:str('scenario_note')};}const selected=(state.cache.planExperiments??[]).find((e:Json)=>e.id===str('experiment_id'));const experiment=str('experiment_id')?selectedExperimentRequest(selected,str('dataset_id'),scopedDatasets()):null;if(experiment){if(selected.payload.request.kind==='forecast'){delete execution.forecast;delete execution.forecast_metric;delete execution.horizon;}else delete execution.scenario;}const selectedComparison=(state.cache.planComparisons??[]).find((r:Json)=>r.id===str('comparison_artifact_id'));const comparisonArtifact=str('comparison_artifact_id')?selectedComparisonRequest(selectedComparison,str('dataset_id'),scopedDatasets(),state.identity):null;const payload={execution,experiment,comparison_artifact:comparisonArtifact,identity_id:state.identity,dataset_id:str('dataset_id'),query:str('query'),mode:str('mode'),comparison:comparisonArtifact?selectedComparison.payload.comparison:str('comparison'),use_llm:check('use_llm'),provider:str('provider'),max_calls:Number(str('max_calls')||2),include_memory:check('include_memory'),include_history:check('include_history'),session_id:str('session_id'),success_criteria:str('success_criteria')};state.query=payload.query;const row=await workspace('/plans','POST',payload);if(sameContext()){if(current())navigate('agents:plan-'+row.id,true);else toast('计划已保存；保留你当前的页面和输入，可从计划列表查看。');}break;}
 case 'execute-plan-form':{const sameContext=contextGuard();const current=unchangedInputGuard(interactionGuard(),()=>form.isConnected?JSON.stringify([...new FormData(form)]):null);const p=state.cache.plan;const r=await workspace('/plans/'+p.id+'/execute','POST',{version:p.version,fingerprint:p.payload.fingerprint,external_consent:check('external_consent')});if(sameContext()){if(current())navigate('agents:run-'+r.id,true);else toast('执行已获批准；保留你当前的页面和输入，可从执行记录查看。');}break;}
 case 'template-form':await workspace('/templates','POST',{name:str('name'),query:str('query'),mode:str('mode'),success_criteria:str('success_criteria')});changed=true;break;
 case 'experiment-form':{const sameContext=contextGuard();const current=unchangedInputGuard(interactionGuard(),()=>form.isConnected?JSON.stringify([...new FormData(form)]):null);const d=scopedDatasets().find(d=>d.id===str('dataset_id'));if(!d)throw new Error('请选择当前身份可访问的数据集');const payload:Json={dataset_id:d.id,dataset_version:d.version,dataset_hash:d.content_hash,target_period:str('target_period')||null,name:str('name'),kind:str('kind'),assumptions:str('assumptions')};if(payload.kind==='scenario')Object.assign(payload,{price_change:val('price_change')!/100,cost_change:val('cost_change')!/100,volume_change:val('volume_change')!/100,fixed_cost_share:val('fixed_cost_share')!/100});else Object.assign(payload,{metric:str('metric'),horizon:val('horizon')});const r=await workspace('/experiments','POST',payload);if(sameContext()){if(current())navigate('lab:'+r.id,true);else toast('实验已保存；保留你当前的页面和输入，可从实验列表查看。');}break;}
 case 'compare-form':{const ids=list('dataset_ids');const members=displayedComparisonMembers(f,scopedDatasets());const mode=str('comparison');const sameContext=contextGuard();const current=unchangedInputGuard(interactionGuard(),()=>form.isConnected?JSON.stringify({selection:[...new FormData(form)],draft:document.querySelector<HTMLFormElement>('#comparison-save-form')?[...new FormData(document.querySelector<HTMLFormElement>('#comparison-save-form')!)]:null}):null);const r=await api('/compare','POST',{dataset_ids:ids,comparison:mode});if(!sameContext())break;if(!current()){toast('对照读取已完成；保留你当前的选择和保存草稿，需要时可重新对照。');break;}const old=document.querySelector<HTMLFormElement>('#comparison-save-form');const oldDraft=old?new FormData(old):null;const draft=comparisonPreviewDraft(r,members,mode,state.identity);document.querySelector('#comparison-output')!.innerHTML=comparisonOutput(r)+comparisonSaveForm({...draft,name:oldDraft?.get('name')??'',comparability_note:oldDraft?.get('comparability_note')??''});break;}
 case 'comparison-save-form':{const sameContext=contextGuard();const current=unchangedInputGuard(interactionGuard(),()=>form.isConnected?JSON.stringify([...new FormData(form)]):null);const payload=comparisonCreateRequest(f,state.identity,form.dataset.requestId??'');const row=await workspace('/comparisons','POST',payload);if(sameContext()){if(current())navigate('compare:'+row.id,true);else{renewSavedDraft(JSON.stringify([...f]),()=>form.isConnected?JSON.stringify([...new FormData(form)]):null,()=>{form.dataset.requestId=crypto.randomUUID();});toast('上一版企业对照已保存；保留你当前的页面和输入，可从已保存对照中查看。');}}break;}
 case 'comparison-delete-form':{if(!check('confirm_delete'))throw new Error('请先核对并确认永久删除及关联影响');const target=comparisonRemovalTarget(form.dataset.id??'',Number(form.dataset.version),form.dataset.identityId??'',form.dataset.source==='history'?'history':undefined);const removed=await removeSavedComparison(target,()=>{refreshComparisonReferences(document,target);forgetCopilotComparison(target);});if(removed){if(submittedCurrent()){modal.close();if(state.route==='compare'&&state.id===target.id)navigate('compare',true);}toast('企业对照已永久清理；历史冻结结果保留，关联计划后续外发将停止。');}break;}
 case 'comparison-transfer-form':{if((form.dataset.identityId??'')!==state.identity)throw new Error('服务身份已经变化，请重新选择企业对照');const row=state.cache.comparison;if(!row||row.id!==form.dataset.id||row.version!==Number(form.dataset.version)||row.comparison_hash!==form.dataset.hash)throw new Error('当前显示的对照已变化，请重新打开');selectedComparisonRequest(row,str('primary_dataset_id'),scopedDatasets(),state.identity);navigate('agents:comparison-'+row.id+':'+str('primary_dataset_id'),true);break;}
 case 'report-compare-form':{if(str('left')===str('right'))throw new Error('请选择两份不同的报告');if(!submittedCurrent())break;const output=document.querySelector<HTMLElement>('#report-comparison')!;output.innerHTML=notice('正在读取两份报告的冻结结果…');try{const r=await workspace('/reports/compare?left='+encodeURIComponent(str('left'))+'&right='+encodeURIComponent(str('right')));if(!submittedCurrent())break;output.innerHTML=reportComparisonView(r);const header=output.closest('dialog')?.querySelector('.dialog-head');output.style.scrollMarginTop=((header?.getBoundingClientRect().height??0)+12)+'px';output.scrollIntoView({block:'start',behavior:'auto'});output.focus({preventScroll:true});}catch(error){if(!submittedCurrent())break;output.innerHTML=notice('本次比较未完成，请核对错误后重新查看差异。','warm');throw error;}break;}
 case 'action-form':{const saved=await workspace('/actions','POST',{request_id:form.dataset.requestId??null,...formSource(f,form.dataset.datasetId??''),identity_id:form.dataset.identityId??'',title:str('title'),company:str('company'),owner:str('owner'),priority:str('priority'),due_at:str('due_at')||null,description:str('description'),acceptance:str('acceptance'),source_key:form.dataset.sourceKey??'',run_id:form.dataset.runId??'',dataset_id:form.dataset.datasetId??''});if(submittedContext()&&renewSavedDraft(JSON.stringify([...f]),()=>form.isConnected?JSON.stringify([...new FormData(form)]):null,()=>{if(!continueInsightDraft(form,saved))form.dataset.requestId=crypto.randomUUID();}))savedDraftMessage=form.dataset.sourceKey?'原行动已保存；保留新草稿，请按表单提示明确修改原行动。':'上一版行动已保存到跟进行动；保留你的新草稿，再次提交将创建新的行动。';changed=true;break;}
 case 'action-edit-form':{const saved=await workspace('/actions/'+form.dataset.id,'PUT',{version:Number(form.dataset.version),title:str('title'),owner:str('owner'),priority:str('priority'),due_at:str('due_at')||null,description:str('description'),acceptance:str('acceptance'),note:str('note')});if(submittedContext()&&form.isConnected)form.dataset.version=String(saved.version);changed=true;break;}
 case 'action-transition-form':await workspace('/actions/'+form.dataset.id+'/status','PUT',{version:Number(form.dataset.version),status:str('status'),note:str('note'),evidence_ids:list('evidence_ids'),evidence_refs:JSON.parse(form.dataset.evidenceRefs??'[]').filter((r:Json)=>list('evidence_ids').includes(r.id))});changed=true;break;
 case 'preferences-form':{const r=await api('/preferences','PUT',{name:str('name'),role:str('role'),theme:str('theme'),amount_unit:str('amount_unit'),risk_appetite:str('risk_appetite'),horizon:str('horizon'),memory_enabled:check('memory_enabled'),interests:split(str('interests')),watchlist:split(str('watchlist')),version:state.user.version});if(submittedCurrent())state.user=r.user;changed=true;break;}
 case 'company-profile-form':await workspace('/profiles','POST',{company:form.dataset.company,version:Number(form.dataset.version),sector:str('sector'),objective:str('objective'),focus:list('focus'),margin_floor:val('margin_floor',true)==null?null:val('margin_floor')!/100,cash_floor:val('cash_floor',true)==null?null:val('cash_floor')!/100,leverage_ceiling:val('leverage_ceiling',true)==null?null:val('leverage_ceiling')!/100,stale_after_days:val('stale_after_days')});changed=true;break;
 case 'password-form':await api('/auth/password','POST',{current_password:str('current_password'),new_password:str('new_password')});resetAuth();toast('密码已修改，所有会话已退出，请重新登录。');break;
 case 'delete-account-form':if(str('confirmation')!=='删除全部数据')throw new Error('请完整输入确认短语');await api('/account','DELETE',{email:state.user.email,password:str('password')});resetAuth();toast('账户与所属数据已删除。');break;
 case 'assistant-form':await ask(str('query'));break;
 case 'claim-review-form':await workspace('/runs/'+state.cache.run.id+'/reviews','POST',{claim_id:form.dataset.id,version:Number(form.dataset.version),verdict:str('verdict'),note:str('note')});changed=true;break;
 case 'dismiss-insight-form':await workspace('/insights/dismiss','POST',{identity_id:state.identity,key:form.dataset.key,note:str('reason')});changed=true;break;
 default:throw new Error('未识别的表单，未执行任何写入。');
 }
 if(changed&&submittedContext()){
  try{
   const applied=await finishMutation(()=>submittedContext()&&submittedCurrent(),refreshData,()=>{state.dirty=false;if(modal.open)modal.close();if(inspector.open)inspector.close();});
   if(!submittedContext())return;
   if(applied){await render();toast(form.id==='preferences-form'?'个人偏好已保存。':'已保存。');}
   else{syncPending=true;showSyncNotice();toast(savedDraftMessage||'已保存；保留你当前的页面和输入，稍后可刷新核对。');}
  }catch(e){
   if(!submittedContext())return;
   if(e instanceof ApiError&&e.status===401){resetAuth();toast('内容已保存，但登录已失效；请重新登录后核对。',true);return;}
   if(submittedCurrent()){form.dataset.saved='true';state.dirty=false;if(modal.open)modal.close();if(inspector.open)inspector.close();}
   syncPending=true;showSyncNotice();toast('内容已保存，但同步读取未完成；请核对并刷新，无需重复提交。',true);
  }
 }
 }catch(e){if(form.id==='comparison-delete-form'&&(!submittedContext()||!submittedCurrent()))return;const msg=e instanceof Error?e.message:'操作失败';if(error&&error.isConnected)error.textContent=msg;else toast(msg,true);if(e instanceof ApiError&&e.status===401&&form.id!=='auth-form'&&form.id!=='password-form')toast('会话已失效。当前输入未自动丢弃，请保存内容后重新登录。',true);}
 finally{form.dataset.submitting='false';if(submit)submit.disabled=form.dataset.saved==='true';}
});
document.addEventListener('click',async(event)=>{const el=(event.target as Element).closest<HTMLElement>('[data-action],[data-route]');if(!el)return;if(el.dataset.route&&el.dataset.action!=='assistant-route'){event.preventDefault();navigate(el.dataset.route);return;}const act=el.dataset.action;const id=el.dataset.id??'';if(el.dataset.pending==='true'||el instanceof HTMLButtonElement&&el.disabled)return;el.dataset.pending='true';el.setAttribute('aria-busy','true');if(['data-quality','data-lineage','data-revisions','assessment-dialog','node-details','archive-dialog','action-detail'].includes(act??''))invalidateInteractions();const valid=interactionGuard();
 try{switch(act){
 case 'close-modal':invalidateInteractions();modal.close();break;case 'close-inspector':invalidateInteractions();inspector.close();break;
 case 'auth-toggle':signingUp=!signingUp;auth();break;
 case 'logout':if(!safeToLeave())return;await api('/auth/logout','POST',{});resetAuth();break;
 case 'go-ops':navigate('ops');break;
 case 'sync-refresh':if(!safeToLeave())return;state.dirty=false;await refreshData();syncPending=false;await render();break;
 case 'archive-dialog':await showArchive();break;
 case 'archive-delete':if(confirm('删除该条记录？独立保存的报告、计划或实验快照不会被连带删除。')){await workspace('/archive/'+el.dataset.kind+'/'+id+'?version='+encodeURIComponent(el.dataset.version??''),'DELETE');await showArchive();toast('所选记录已删除。');}break;
 case 'menu':toggleNav();break;
 case 'close-menu':toggleNav(false);break;
 case 'show-assistant':toggleAssistant();void mountCopilot().catch(()=>{});break;
 case 'close-assistant':toggleAssistant(false);break;
 case 'refresh':if(!state.user){await bootstrap();await render();break;}if(!safeToLeave())return;state.dirty=false;await refreshData();await render();break;
 case 'command':dialog('快速前往',`<input id="command-filter" placeholder="搜索工作区…" aria-label="搜索工作区" autofocus><div id="command-results" class="command-results">${Object.entries(routes).map(([k,r])=>`<button class="list-link" data-route="${k}">${icon(r.icon)}<span>${r.label}</span>${icon('chevron')}</button>`).join('')}</div>`);break;
 case 'new-dataset':if(!safeToLeave())return;state.dirty=false;dialog('新建经营数据',datasetEditor(null),true);break;
 case 'select-dataset':if(!safeToLeave())return;invalidateContext();state.cache={};state.active=id;state.dirty=false;await render();break;
 case 'import-dialog':state.cache.importDraft=null;dialog('导入自己的经营数据',importForm());break;
 case 'add-period':{const form=el.closest('form');form?.querySelector('#period-rows')?.insertAdjacentHTML('beforeend',periodRow({},form.querySelectorAll('[data-period-row]').length));state.dirty=true;break;}
 case 'remove-period':{const form=el.closest('form'),row=el.closest('[data-period-row]');if(form&&row&&form.contains(row)){row.remove();state.dirty=true;}break;}
 case 'stage-back':if(state.cache.editorDraft){dialog('继续编辑数据',datasetEditor(state.cache.editorDraft),true);modal.querySelector<HTMLSelectElement>('[name="basis"]')!.value=state.cache.editorDraft.basis;}else dialog('重新选择导入文件',importForm(state.cache.importDraft??{}));break;
 case 'commit-stage':{
  const p=state.cache.stage,label=el.textContent,sameContext=contextGuard();
  const feedback=modal.querySelector<HTMLElement>('[data-import-stage-error]');
  if(feedback)feedback.textContent='';
  let saved=false;el.setAttribute('disabled','');el.textContent='正在保存并同步…';
  try{
   const d=await workspace('/imports/'+p.id+'/commit','POST',{version:p.version,fingerprint:p.payload.fingerprint});saved=true;
   const applied=await finishMutation(()=>valid()&&sameContext(),refreshData,()=>{state.active=d.id;state.dirty=false;modal.close();navigate('data',true);});
   if(!sameContext())break;
   if(!applied){syncPending=true;showSyncNotice();}
   toast(applied?'已保存标准化数据和修订记录。':'数据已保存；保留你当前的页面和输入，可核对并刷新。');
  }catch(e){
   if(!sameContext())break;
   if(!saved){
    if(!valid()||(feedback&&!feedback.isConnected)){
     const refusals:Record<string,number>={PREVIEW_INTEGRITY:409,PREVIEW_MISMATCH:409,PREVIEW_EXPIRED:409,VERSION_CONFLICT:409,RESOURCE_LIMIT:409,NOT_FOUND:404,UNAUTHORIZED:401,CSRF_REJECTED:403};
     const refused=e instanceof ApiError&&refusals[e.code]===e.status;
     if(!refused)toast('上一份数据预览的保存结果未能确认。请核对当前数据和修订记录；不要重复导入。',true);
     break;
    }
    // The native dialog is above the global toast layer. Keep a failed or
    // uncertain save with this exact preview, including its recovery controls.
    if(valid()&&feedback?.isConnected){
     feedback.textContent=e instanceof Error?e.message:'保存结果无法确认，请核对当前数据后再操作。';
     const group=feedback.parentElement??feedback;
     group.style.scrollMarginTop=((modal.querySelector('.dialog-head')?.getBoundingClientRect().height??0)+12)+'px';
     group.scrollIntoView({block:'nearest',behavior:'auto'});feedback.focus({preventScroll:true});
     break;
    }
    throw e;
   }
   if(e instanceof ApiError&&e.status===401){resetAuth();toast('数据已保存，但登录已失效；请重新登录后核对。',true);break;}
   if(valid()){state.dirty=false;modal.close();}
   syncPending=true;showSyncNotice();toast('数据已保存，但同步读取未完成，请核对并刷新；无需重复导入。',true);
  }finally{el.removeAttribute('disabled');el.textContent=label;}
  break;
 }
 case 'data-quality':{const quality=await workspace('/datasets/'+state.active+'/quality');if(valid())inspect('数据质量与缺项',qualityPanel(quality));break;}
 case 'data-lineage':{const r=await workspace('/datasets/'+state.active+'/lineage');if(!valid())break;inspect('指标血缘',r.items.map((l:Json)=>`<details><summary>${esc(l.label)} · ${metricValue(l.id,l.value)}</summary><code>${esc(l.formula)}</code>${jsonView(l.inputs)}</details>`).join(''));break;}
 case 'data-revisions':{const r=await workspace('/datasets/'+state.active+'/revisions');if(!valid())break;dialog('数据修订记录',revisionHistory(r.items),true);break;}
 case 'restore-revision':{
  if(!confirm('确认恢复此历史内容并创建新的数据修订？'))return;
  const sameContext=contextGuard();let saved=false;
  try{
   await workspace('/datasets/'+state.active+'/restore','POST',{version:activeDataset().version,target_revision:Number(el.dataset.revision)});saved=true;
   const applied=await finishMutation(()=>sameContext()&&valid(),refreshData,()=>{state.dirty=false;modal.close();});
   if(!sameContext())break;
   if(applied){await render();toast('已恢复为新的修订。');}
   else{syncPending=true;showSyncNotice();toast('已恢复为新的修订；保留你当前的页面和输入，可核对并刷新。');}
  }catch(e){
   if(!sameContext())break;if(!saved)throw e;
   if(e instanceof ApiError&&e.status===401){resetAuth();toast('历史内容已恢复，但登录已失效；请重新登录后核对。',true);break;}
   if(valid()){state.dirty=false;modal.close();}
   syncPending=true;showSyncNotice();toast('历史内容已恢复，但同步读取未完成；请核对并刷新，无需重复恢复。',true);
  }
  break;
 }
 case 'export-dataset':location.href='/api/datasets/'+state.active+'/export';break;
 case 'delete-dataset':if(!confirm('删除数据集及修订历史？被运行引用的数据需先清理对应会话。'))return;await api('/datasets/'+id+'?version='+encodeURIComponent(el.dataset.version??''),'DELETE');await refreshData();await render();break;
 case 'evidence-dialog':dialog('添加原始资料',evidenceForm(),true);break;
 case 'review-evidence':dialog('审阅与适用范围',reviewEvidenceForm(state.cache.evidence.find((d:Json)=>d.id===id)),true);break;
 case 'edit-evidence-metadata':dialog('编辑资料元数据',evidenceMetadataForm(state.cache.evidence.find((d:Json)=>d.id===id)),true);break;
 case 'evidence-detail':{const d=state.cache.evidence.find((v:Json)=>v.id===id);inspect(d.payload.title,`<p class="micro">资料 ID：<code>${esc(d.id)}</code></p><p class="micro">内容 SHA-256：${esc(d.content_hash)}</p><p>${esc(d.payload.source_url||'未提供来源链接')}</p><p class="micro">来源类型：${esc(d.payload.source_kind)} · 核验状态：${esc(d.payload.verification)}<br>原始获取地址：${esc(d.payload.original_source_url??d.payload.source_url??'未提供')}<br>获取时间：${esc(d.payload.retrieved_at??d.payload.fetched_at??'未记录')}</p>${button('编辑元数据','edit-evidence-metadata','secondary',`data-id="${id}"`)}${status(d.review.status)}<pre class="source-text">${esc(d.payload.text)}</pre>${button('审阅此资料','review-evidence','primary',`data-id="${id}"`)}`);break;}
 case 'delete-evidence':if(!confirm('删除原始资料？历史报告仍保留当时的引用快照；新任务将不再使用。'))return;await api('/evidence/'+id+'?version='+encodeURIComponent(el.dataset.version??''),'DELETE');await render();break;
 case 'document-dialog':dialog('上传原始文档',`<form id="document-form" class="stack">${field('标题',input('title','','required maxlength="200"'))}${evidenceScope()}${field('来源地址',input('source_url','','type="url"'))}${field('发布日期',input('published_at','','type="date"'))}<label class="upload-box">${icon('upload')}<strong>选择文本资料</strong><span>TXT / MD${state.caps.pdf.enabled?' / 文本型 PDF':''} · 最大 2 MB</span><input type="file" name="file" accept=".txt,.md${state.caps.pdf.enabled?',.pdf':''}" required></label>${state.caps.pdf.enabled?'':notice('当前 PDF 解析依赖未通过版本门禁。请使用 TXT / MD；不静默调用外部 OCR。','warm')}${formFooter('解析并保存')}</form>`);break;
 case 'public-search-dialog':dialog('公开资料检索',`<form id="public-search-form" class="stack">${field('检索内容',input('query',activeDataset()?.payload.company??'','required minlength="2" maxlength="500"'))}<label class="check-label consent"><input type="checkbox" name="consent" required>同意将此查询词发送给已配置的公开搜索服务，不发送财务表和记忆。</label>${formFooter('发起公开检索')}</form><div id="public-search-results"></div><details><summary>按已知公开 URL 获取原文</summary><form id="fetch-evidence-form" class="stack">${field('标题',input('title','','required'))}${field('白名单来源 URL',input('url','','required type="url" placeholder="https://…"'))}${field('发布日期',input('published_at','','type="date"'))}${evidenceScope()}${formFooter('获取公开原文')}</form></details>`,true);break;
 case 'save-search-result':{const r=state.cache.search.items[Number(el.dataset.index)];state.cache.searchCapture=r;dialog('保存搜索摘要',`<form id="search-evidence-form" class="stack"><h3>${esc(r.title)}</h3>${notice('保存的是未经核验的搜索摘要，来源标签和获取时间将保留。')}${evidenceScope()}${formFooter('保存到证据库')}</form>`);break;}
 case 'memory-dialog':dialog('添加长期记忆',memoryForm());break;
 case 'edit-memory':dialog('修改记忆',memoryForm(state.cache.memories.find((v:Json)=>v.id===id)));break;
 case 'toggle-memory':{const m=state.cache.memories.find((v:Json)=>v.id===id);await api('/memories/'+id,'PUT',{...m.payload,version:m.version,approved:!m.payload.approved});await render();break;}
 case 'delete-memory':if(!confirm('删除记忆？今后不再召回，历史运行中已冻结的内容仍保留。'))return;await api('/memories/'+id+'?version='+encodeURIComponent(el.dataset.version??''),'DELETE');await render();break;
 case 'fill-query':{const q=el.dataset.query??el.textContent??'';const area=document.querySelector<HTMLTextAreaElement>('#plan-form [name="query"]');if(area){area.value=q;area.focus();state.dirty=true;}break;}
 case 'replay-intro':showBrandIntro(true);break;
 case 'graph-toggle':{const host=el.closest('.graph-shell')!;const list=host.querySelector<HTMLElement>('.graph-list')!;list.hidden=!list.hidden;host.querySelector<HTMLElement>('.graph-scroll')!.hidden=!list.hidden;break;}
 case 'graph-minus':case 'graph-plus':{const e=el.closest('.graph-shell')?.querySelector<HTMLElement>('.graph-scroll');if(e){const classes=['zoom-small','zoom-normal','zoom-large'];let i=classes.findIndex(c=>e.classList.contains(c));i=Math.min(2,Math.max(0,i+(act==='graph-plus'?1:-1)));classes.forEach(c=>e.classList.remove(c));e.classList.add(classes[i]);}break;}
 case 'pause-run':case 'resume-run':{const rt=await workspace('/runs/'+id+'/runtime');await workspace('/runs/'+id+'/control','POST',{version:rt.control.version,action:act==='pause-run'?'pause':'resume'});await render();break;}
 case 'assessment-dialog':{const r=await workspace('/runs/'+state.cache.run.id+'/assessment');if(!valid())break;dialog('报告验收与回放授权',assessmentForm(r.item,r.review_context));break;}
 case 'delete-strategy':case 'delete-evaluation':{if(!confirm('清理此候选或回放记录？清理后不可恢复，历史报告保持不变；当前策略和回滚链不能清理。'))return;await workspace((act==='delete-strategy'?'/strategies/':'/strategy-evaluations/')+id+'?version='+el.dataset.version,'DELETE');await render();break;}
 case 'strategy-propose':await workspace('/evolution/propose','POST',{});await render();break;
 case 'strategy-dialog':dialog('建立编排策略候选',strategyForm());break;
 case 'strategy-evaluate':await workspace('/strategies/'+id+'/evaluate','POST',{});await render();break;
 case 'evaluation-detail':{const r=state.cache.evolution.evaluations.find((x:Json)=>x.id===id);inspect('逐例回放与门槛依据',jsonView(r.payload));break;}
 case 'strategy-activate':{if(!confirm('仅对未来计划激活该策略？既有报告保持不变，未执行旧计划需要重新生成。'))return;const latest=await workspace('/evolution');await workspace('/strategies/'+id+'/activate','POST',{evaluation_id:el.dataset.evaluation,expected_active_version:latest.active?.version??0});await render();break;}
 case 'strategy-rollback':{if(!confirm('回滚到上一策略？旧报告不变，未执行计划需要重新核对。'))return;await workspace('/strategies/rollback','POST',{expected_active_version:state.cache.evolution.active.version});await render();break;}
 case 'cancel-plan':await workspace('/plans/'+id+'/cancel?version='+encodeURIComponent(el.dataset.version??''),'POST',{});await render();break;
 case 'cancel-run':await api('/runs/'+id+'/cancel','POST',{});await render();break;
 case 'node-details':{if(state.route==='agents'&&state.id.startsWith('run-')){const audit=await workspace('/runs/'+state.id.slice(4)+'/audit');if(!valid())break;state.cache.audit=audit;}const n=state.cache.nodes?.find((x:Json)=>x.id===id);if(!n)throw new Error('节点不在当前执行计划中');const artifacts=state.cache.audit?.artifacts?.filter((a:Json)=>a.node===id)??[];inspect(n.label??n.name,`<p>${esc(n.purpose)}</p>${badge(n.engine==='optional_llm'?'模型专家':'确定性工具')}<h3>依赖与工具边界</h3>${jsonView({capability:n.capability,depends_on:n.depends_on,tools:n.tools,enabled:n.enabled,reason:n.skip_reason??n.reason})}<h3>实际执行产物</h3>${artifacts.length?artifacts.map((a:Json)=>`<details open><summary>可核验产物 · ${timeText(a.created_at)}</summary>${jsonView(a.payload)}<small class="micro">${esc(a.content_hash)}</small></details>`).join(''):notice('当前没有已保存的节点产物。不会显示模型隐藏思考过程或虚构执行日志。')}`);break;}
 case 'run-tab':{document.querySelectorAll<HTMLElement>('.run-tab').forEach(p=>p.hidden=p.id!=='run-tab-'+el.dataset.tab);document.querySelectorAll<HTMLElement>('[data-action="run-tab"]').forEach(b=>{const on=b===el;b.classList.toggle('active',on);b.setAttribute('aria-selected',String(on));b.setAttribute('tabindex',on?'0':'-1');});break;}
 case 'export-audit':download('execution-audit.json',state.cache.audit);break;
 case 'save-template-dialog':dialog('保存任务模板',templateForm());break;
 case 'apply-template':{const t=state.cache.templates.find((v:Json)=>v.id===id).payload;const form=document.querySelector<HTMLFormElement>('#plan-form');if(form){for(const key of ['query','mode','success_criteria']){const e=form.elements.namedItem(key) as HTMLInputElement;if(e)e.value=t[key];}state.dirty=true;form.scrollIntoView({behavior:'smooth',block:'start'});}break;}
 case 'delete-template':if(!confirm('删除此模板？已生成的计划不受影响。'))return;await workspace('/templates/'+id+'?version='+encodeURIComponent(el.dataset.version??''),'DELETE');await render();break;
 case 'export-experiment':download('analysis-experiment.json',state.cache.experiment);break;
 case 'delete-comparison':{const target=comparisonRemovalTarget(id,Number(el.dataset.version),el.dataset.identityId??'',el.dataset.source==='history'?'history':undefined);dialog('确认永久清理企业对照',comparisonDeleteForm(target));break;}
 case 'export-comparison':download('saved-enterprise-comparison.json',state.cache.comparison);break;
 case 'report-compare-dialog':dialog('报告与输入修订对比',reportCompareForm(),true);break;
 case 'action-dialog':dialog('创建跟进行动',actionForm());break;
 case 'action-from-report':{const r=state.cache.run;dialog('从诊断报告创建行动',actionForm({run_id:r.id,dataset_id:r.dataset_id,company:r.snapshot.dataset.company,title:'跟进：'+r.payload.query.slice(0,100),message:r.result.findings.join('\n')}));break;}
 case 'action-detail':{const a=state.cache.actions.find((a:Json)=>a.id===id);const docs=await workspace('/evidence');if(!valid())break;inspect('行动与验收',actionDetail(a,docs.items));break;}
 case 'action-edit':{if(!safeToLeave())break;state.dirty=false;const a=state.cache.actions.find((a:Json)=>a.id===id);inspector.close();dialog('编辑跟进行动',actionEditForm(a));break;}
 case 'insight-action':dialog('把核查项转为行动',actionForm(state.cache.insights.find((i:Json)=>i.key===id)));break;
 case 'insight-details':{const i=state.cache.insights.find((v:Json)=>v.key===id);inspect(i.title,`<p>${esc(i.message)}</p><h3>触发依据</h3>${jsonView(i.proof)}<p class="micro">数据修订 ${i.dataset_version} · 本地确定性规则，不是模型预测。</p><div class="inline-actions">${button('转为行动','insight-action','primary',`data-id="${esc(id)}"`)}${routeButton('打开相关工作区',i.target)}</div><details><summary>本次不再提示</summary><form id="dismiss-insight-form" data-key="${esc(id)}">${field('搁置原因',textarea('reason','','required minlength="5" rows="2"'))}${formFooter('仅对当前身份与本次依据关闭提示')}</form></details>`);break;}
 case 'assistant-query':await ask(el.dataset.query??'');break;
 case 'assistant-route':{const route=el.dataset.route,dataset=el.dataset.datasetId;if(!route||!Object.hasOwn(routes,route))throw new Error('原问题的目标工作区不可用，请重新核查。');if(dataset&&!scopedDatasets().some(d=>d.id===dataset))throw new Error('原问题的企业已不在当前身份范围内，请重新核查。');if(!safeToLeave())break;if(dataset&&dataset!==state.active){invalidateContext();state.cache={};state.active=dataset;}state.query=el.dataset.query??'';navigate(route,true);break;}
 case 'review-claim':{const old=state.cache.reviews.find((r:Json)=>r.payload.claim_id===id);dialog('人工复核模型解释',`<form id="claim-review-form" class="stack" data-id="${esc(id)}" data-version="${old?.version??0}">${field('复核结论',select('verdict',{accepted:'接受，依据已记录',rejected:'不接受',needs_evidence:'需要补充证据'},old?.payload.verdict??'needs_evidence'))}${field('核对依据 / 反向证据',textarea('note',old?.payload.note??'','rows="5" required minlength="5"'))}${formFooter('记录人工复核')}</form>`);break;}
 case 'password-dialog':dialog('修改密码',`<form id="password-form" class="stack">${field('当前密码',input('current_password','','type="password" autocomplete="current-password" required'))}${field('新密码',input('new_password','','type="password" autocomplete="new-password" required minlength="12" maxlength="128"'))}${notice('修改后将吊销全部登录会话，包括当前会话。')}${formFooter('修改并退出所有会话')}</form>`);break;
 case 'delete-account-dialog':dialog('删除账户与全部数据',`<form id="delete-account-form" class="stack">${notice('永久删除账户、数据、证据、记忆、报告及审计记录，无法在应用内撤销。先导出重要数据。','danger')}${field('当前密码',input('password','','type="password" autocomplete="current-password" required'))}${field('输入“删除全部数据”确认',input('confirmation','','required'))}${formFooter('永久删除')}</form>`);break;
 case 'delete-conversation':if(!confirm('永久删除此会话、关联报告与执行记录？进行中的任务会被取消。'))return;await api('/conversations/'+id+'?version='+encodeURIComponent(el.dataset.version??''),'DELETE');await render();break;
 default:throw new Error('此操作尚未识别，没有执行任何写入：'+act);
 }}catch(e){toast(e instanceof Error?e.message:'操作失败',true);}finally{delete el.dataset.pending;el.removeAttribute('aria-busy');}
});
document.addEventListener('input',(event)=>{const el=event.target as HTMLInputElement;if(el.id==='command-filter'){document.querySelectorAll<HTMLElement>('#command-results button').forEach(b=>b.hidden=!b.textContent!.includes(el.value));return;}const form=el.closest('form');if(form&&!['auth-form','assistant-form','evidence-search','compare-form','comparison-delete-form','public-search-form'].includes(form.id))state.dirty=true;});
document.addEventListener('change',async(event)=>{const el=event.target as HTMLInputElement;try{if(el.closest('#report-compare-form')&&['left','right'].includes(el.name)){const form=el.closest('form')!,left=form.querySelector<HTMLSelectElement>('[name="left"]')!.value,right=form.querySelector<HTMLSelectElement>('[name="right"]')!.value;form.querySelector('#report-selection-details')!.innerHTML=reportSelectionDetails(left,right);const output=form.parentElement?.querySelector('#report-comparison');if(output)output.innerHTML=notice('报告选择已改变，请重新查看差异。');const error=form.querySelector('.form-error');if(error)error.textContent='';}if(el.id==='plan-experiment')syncExperimentControls(document,state.cache.planExperiments??[],scopedDatasets());if(el.id==='plan-comparison'||el.closest('#plan-form')&&el.name==='dataset_id')syncComparisonControls(document,state.cache.planComparisons??[],scopedDatasets(),state.identity);if(el.id==='active-dataset'){if(!safeToLeave()){el.value=state.active;return;}invalidateContext();state.cache={};state.active=el.value;state.dirty=false;await render();}if(el.id==='role-switch'){if(!safeToLeave()){el.value=state.user.preferences.role;return;}try{const r=await api('/preferences/role','PUT',{role:el.value,version:state.user.version});invalidateContext();state.user=r.user;state.cache={};state.dirty=false;await render();toast('工作视角已切换');}catch(e){el.value=state.user.preferences.role;throw e;}}if(el.id==='extra-fields')el.closest('form')?.querySelector('.editor-table')?.classList.toggle('expanded',el.checked);if(el.id==='use-llm'){const e=document.querySelector<HTMLElement>('#model-options');if(e)e.hidden=!el.checked;}if(el.id==='experiment-kind'){for(const kind of ['scenario','forecast']){const fields=document.querySelector<HTMLFieldSetElement>('#'+kind+'-fields')!;fields.hidden=el.value!==kind;fields.disabled=el.value!==kind;}}}catch(e){toast(String(e),true);}});
for(const overlay of [modal,inspector])overlay.addEventListener('cancel',()=>invalidateInteractions());
document.querySelector('.skip-link')?.addEventListener('click',e=>{e.preventDefault();document.querySelector<HTMLElement>('#main')?.focus();});
window.addEventListener('hashchange',()=>{if(state.dirty&&!safeToLeave()){history.replaceState(null,'',currentHash||'#brief');return;}invalidateInteractions();closeDrawers();if(modal.open)modal.close();if(inspector.open)inspector.close();state.dirty=false;void render();});
window.addEventListener('beforeunload',e=>{if(state.dirty){e.preventDefault();e.returnValue='';}});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'&&state.user){e.preventDefault();document.querySelector<HTMLElement>('[data-action="command"]')?.click();}if((e.key==='ArrowRight'||e.key==='ArrowLeft')&&(e.target as HTMLElement).getAttribute('role')==='tab'){e.preventDefault();const tabs=[...document.querySelectorAll<HTMLButtonElement>('[role="tab"]')];const i=tabs.indexOf(e.target as HTMLButtonElement);const t=tabs[(i+(e.key==='ArrowRight'?1:tabs.length-1))%tabs.length];t.click();t.focus();}});
// Poll only the currently viewed run. No periodic paid requests, no overwrite of draft forms.
setInterval(async()=>{if(polling||document.hidden||!state.user||state.route!=='agents'||!state.id.startsWith('run-')||state.dirty||modal.open||inspector.open)return;const r=state.cache.run;if(!r||r.snapshot?.studio?.adaptive||!['queued','running'].includes(r.state))return;polling=true;try{const latest=await api('/runs/'+r.id);if(state.id!=='run-'+r.id)return;if(latest.state!==r.state||latest.result){await render();}else{const audit=await workspace('/runs/'+r.id+'/audit');state.cache.audit=audit;const node=document.querySelector('#live-run-status');if(node)node.textContent=`已记录 ${audit.trace.length} 个执行事件；最新更新 ${timeText(latest.updated_at)}`;}}catch(e){const node=document.querySelector('#live-run-status');if(node)node.textContent='状态同步暂时失败；不会将连接中断视为任务成功。';}finally{polling=false;}},1500);
setupExperience({dialog,inspect,toast,navigate,navigateRendered,render,refresh:refreshData,reset:resetAuth});
restoreMotion();showBrandIntro();
(async()=>{try{await bootstrap();await render();}catch(e){if(e instanceof ApiError&&e.status===401)auth();else{root.innerHTML=`<main class="startup-error">${heading('暂时无法连接服务','输入和账户不会被模拟状态替代。')}${notice(e instanceof Error?e.message:'连接失败','danger')}${button('重新连接','refresh','primary')}</main>`;}}})();

function showSyncNotice(){const el=document.querySelector<HTMLElement>('#sync-notice');if(!el)return;el.hidden=!syncPending;if(syncPending)el.innerHTML=`<div class="sync-bar"><span>工作区有已保存的变更。当前未保存输入不会自动覆盖。</span>${button('核对并刷新','sync-refresh','text-button')}</div>`;}
async function checkSync(){if(syncing||!state.user||document.hidden)return;const owner=state.user.id;syncing=true;try{const r=await api('/sync?after='+state.cursor+'&limit=100');if(state.user?.id!==owner)return;state.cursor=r.cursor;if(r.items.length){syncPending=true;showSyncNotice();}}catch(e){if(e instanceof ApiError&&e.status===401)resetAuth();}finally{syncing=false;}}
async function showArchive(){const valid=interactionGuard();const r=await workspace('/archive');if(!valid())return;dialog('管理已保存记录',notice(r.notice)+Object.entries(r.collections).map(([kind,collection]:[string,Json])=>`<details><summary>${esc(({plan:'执行计划',experiment:'研究实验',action:'行动记录',import_stage:'导入预览',dismissal:'忽略的核查项'} as Record<string,string>)[kind])} · ${collection.total}</summary>${collection.items.length?table(['记录','状态','操作'],collection.items.map((v:Json)=>[esc(v.label),status(v.status),button('删除','archive-delete','text-button danger-text',`data-kind="${esc(kind)}" data-id="${esc(v.id)}" data-version="${v.version}"`)])):'<p class="muted">暂无记录。</p>'}${collection.has_more?notice('仅显示最近100条，删除后可继续整理较早记录。'):''}</details>`).join(''),true);}
setInterval(()=>void checkSync(),15000);
window.addEventListener('online',()=>void checkSync());

function appearancePanel(){return `<section class="panel motion-settings"><div class="row-between"><h2>品牌与动效</h2>${button('重播原始开场','replay-intro')}</div><p class="micro">保留原始标识与视频。动画可跳过；无法播放、减少动效或存储不可用都不影响登录与工作。</p><form id="appearance-form" class="stack">${field('动效偏好',select('motion',{system:'跟随系统',reduce:'减少动效',full:'完整动效'},document.documentElement.dataset.motion??'system'))}${formFooter('应用动效偏好')}</form></section>`;}
function setupLive(){
 const rt=state.cache.runtime,run=state.cache.run;
 if(state.route!=='agents'||!state.id.startsWith('run-')||!run?.snapshot?.studio?.adaptive||!rt||(!['queued','running','pause_requested'].includes(rt.state)&&!['queued','running'].includes(run.state)))return;
 const runId=run.id,owner=state.user.id;
 live=new RunLive(runId,(runtime,trace)=>{
   if(state.user?.id!==owner||state.id!=='run-'+runId)return;
   state.cache.runtime=runtime;state.cache.nodes=runtime.graph.payload.nodes;state.cache.audit.trace=trace;
   const focused=(document.activeElement as HTMLElement)?.dataset?.node;
   const scrolls=[...document.querySelectorAll<HTMLElement>('[data-live-graph]')].map(e=>e.querySelector('.graph-scroll')?.scrollTop??0);
   document.querySelectorAll<HTMLElement>('[data-live-graph]').forEach((e,i)=>{e.innerHTML=graphCanvas(runtime.graph.payload.nodes,trace,runtime.state);const sc=e.querySelector('.graph-scroll');if(sc)sc.scrollTop=scrolls[i];});
   const ribbon=document.querySelector('#runtime-ribbon');if(ribbon)ribbon.innerHTML=runtimeRibbon(runtime);
   if(focused)document.querySelector<SVGElement>('[data-node="'+CSS.escape(focused)+'"]')?.focus();
 },()=>{if(state.user?.id===owner&&state.id==='run-'+runId&&!state.dirty)void render();},label=>{const e=document.querySelector('#live-transport');if(e)e.textContent=label;});live.start();
}
document.addEventListener('keydown',e=>{const t=e.target as Element;if((e.key==='Enter'||e.key===' ')&&t.matches('.dag-node')){e.preventDefault();t.dispatchEvent(new MouseEvent('click',{bubbles:true}));}});
window.addEventListener('offline',()=>{toast('网络已断开。正在编辑的内容保留；未确认成功的写入不会自动重试。',true);});
