import {api,workspace,type Json} from './api.js';
import {state,activeDataset} from './state.js';
import {esc,icon,heading,button,routeButton,badge,status,empty,notice,num,pct,amount,unitName,timeText,lineChart,table,field,input,select,textarea,formFooter,jsonView,metricNames} from './components.js';
export async function briefPage(){
 const b=await workspace('/brief');state.brief=b;const d=activeDataset();const selected=b.datasets.find((x:Json)=>x.id===d?.id);const items=b.insights.items.filter((x:Json)=>!d||x.dataset_id===d.id);state.cache.insights=b.insights.items;
 const analysis=d?await api('/datasets/'+d.id+'/analysis'):null;const u=state.user.preferences.amount_unit;
 return heading('工作简报',d?`${d.payload.company} · ${selected.period} · 以已保存的数据为依据`:'从一份真实数据开始，建立你的企业研究工作区。',routeButton(icon('plus')+' 发起研判','agents','primary'))+
 `<div class="summary-band"><div><span>企业数据集</span><strong>${b.counts.datasets}</strong></div><div><span>可追溯资料</span><strong>${b.counts.evidence}</strong></div><div><span>待跟进行动</span><strong>${b.counts.actions_open}</strong></div><div><span>归档报告</span><strong>${b.counts.reports}</strong></div></div>`+
 (!d?`<section class="onboarding panel"><div class="onboarding-copy"><span class="eyebrow">你的研究，从真实输入开始</span><h2>把数据、证据与判断<br>放在同一个工作流里。</h2><p>先导入企业季度财务数据，再定义研究目标。助手会提示缺项，Agent 会在你批准的边界内工作。</p><div class="inline-actions">${button(icon('upload')+' 导入经营数据','import-dialog','primary')}${routeButton('手动录入 '+icon('arrow'),'data','text-button')}</div></div><div class="onboarding-steps"><div><span>01</span><section><h3>录入与核对</h3><p>检查单位、期间与来源；预览后再入库。</p></section></div><div><span>02</span><section><h3>预览执行计划</h3><p>查看分工、输入证据和外部调用范围。</p></section></div><div><span>03</span><section><h3>留下可复核的结论</h3><p>保留计算血缘、反向证据和后续行动。</p></section></div></div></section>`:
 `<div class="metric-row"><article class="metric"><span class="metric-label">营业收入</span><strong>${amount(selected.revenue,u)}<small>${unitName(u)}</small></strong><span class="metric-note">同比 ${pct(selected.metrics.revenue_growth)}</span></article><article class="metric"><span class="metric-label">毛利率</span><strong>${pct(selected.metrics.gross_margin)}</strong><span class="metric-note">${selected.profile.margin_floor!=null?'企业自定目标 '+pct(selected.profile.margin_floor):'未设置企业目标'}</span></article><article class="metric"><span class="metric-label">经营现金收入比</span><strong>${pct(selected.metrics.cash_ratio)}</strong><span class="metric-note">${selected.metrics.cash_ratio==null?'缺少经营现金流输入':'经营现金流 ÷ 营业收入'}</span></article></div>`)+
 `<div class="brief-grid"><section class="panel"><div class="section-heading row-between"><div><span class="eyebrow">${d?'主动核查':'准备工作'}</span><h2>现在值得关注</h2></div>${badge(items.length+' 项')}</div>${items.length?items.slice(0,6).map((i:Json)=>`<article class="insight"><span class="insight-marker ${i.priority}">${icon(i.code==='evidence'?'files':i.code==='stale'?'clock':'activity')}</span><div class="insight-body"><h3>${esc(i.title)}</h3><p>${esc(i.message)}</p><div class="inline-actions">${button('查看依据','insight-details','text-button',`data-id="${esc(i.key)}"`)}${i.action_id?routeButton('已创建行动','actions','text-button'):button('转为行动 '+icon('arrow'),'insight-action','text-button',`data-id="${esc(i.key)}"`)}</div></div></article>`).join(''):(d?empty('当前规则没有触发待核查项','这不代表企业无风险。完善企业目标和外部证据可扩大检查范围。',routeButton('设置企业目标','settings')):empty('还没有可核查的企业数据','不会用占位数字或模拟结论填充此工作区。'))}${items.length>6?notice('更多核查项可在右侧助手和对应数据工作区查看。'):''}</section>
 <section class="panel"><div class="section-heading row-between"><h2>${d?'收入与成本':'最近研判'}</h2>${d?routeButton('数据详情','data'):''}</div>${analysis?lineChart(analysis.series,[{id:'revenue',name:'营业收入'},{id:'cost',name:'营业成本'}],unitName(u),({yuan:1,wan:1e4,yi:1e8} as Record<string,number>)[u]):empty('暂无执行记录','生成计划、批准执行后，真实状态会在这里出现。')}<div class="section-heading row-between"><h3>最近执行</h3>${routeButton('全部记录','ops')}</div>${b.runs.length?b.runs.slice(0,4).map((r:Json)=>`<button class="list-link" data-route="agents:run-${esc(r.id)}"><span><strong>${esc(r.payload.query)}</strong><small>${timeText(r.created_at)}</small></span>${status(r.state)}</button>`).join(''):'<p class="muted">尚未执行诊断任务。</p>'}</section></div>`;
}
export async function settingsPage(){const profiles=await workspace('/profiles');state.cache.profiles=profiles.items;const d=activeDataset();const p=state.user.preferences;const row=profiles.items.find((x:Json)=>x.payload.company===d?.payload.company);const c=row?.payload??{};
 return heading('偏好与设置','个性化影响服务重点，不改变客观数据、公式与证据标准。')+`<div class="settings-layout"><section class="panel"><h2>个人工作偏好</h2><form id="preferences-form" class="stack"><div class="form-grid">${field('称呼',input('name',state.user.name,'required maxlength="200"'))}${field('工作视角',select('role',{enterprise:'企业经营',investor:'投资研究'},p.role))}${field('金额显示',select('amount_unit',{yuan:'元',wan:'万元',yi:'亿元'},p.amount_unit))}${field('外观',select('theme',{light:'浅色',dark:'深色',system:'跟随系统'},p.theme))}${field('风险关注',select('risk_appetite',{low:'审慎',medium:'均衡',high:'较高容忍'},p.risk_appetite))}${field('关注期限',select('horizon',{short:'短期',medium:'中期',long:'长期'},p.horizon))}</div>${field('关注主题（逗号分隔）',input('interests',p.interests.join('，'),'maxlength="1000"'))}${field('关注企业（逗号分隔）',input('watchlist',p.watchlist.join('，'),'maxlength="2000"'))}<label class="check-label"><input type="checkbox" name="memory_enabled" ${p.memory_enabled?'checked':''}>在明确批准的范围内召回长期记忆</label>${formFooter('保存偏好')}</form></section>
 <section class="panel"><div class="section-heading"><h2>企业研究目标</h2><p class="muted">${d?esc(d.payload.company):'先选择企业数据集'}</p></div>${d?`<form id="company-profile-form" class="stack" data-company="${esc(d.payload.company)}" data-version="${row?.version??0}">${field('产业环节',select('sector',{materials:'上游材料',cells:'电芯制造',equipment:'设备与系统',recycling:'回收利用',other:'其他'},c.sector??'other'))}${field('本期经营 / 研究目标',textarea('objective',c.objective??'','rows="3" maxlength="1000" placeholder="说明你希望解决的实际业务问题"'))}<fieldset><legend>优先关注</legend><div class="check-grid">${Object.entries({margin:'毛利与成本',cash:'现金流',growth:'营收增长',inventory:'库存',leverage:'杠杆',evidence:'证据质量'}).map(([k,l])=>`<label class="check-label"><input type="checkbox" name="focus" value="${k}" ${(c.focus??['margin','cash']).includes(k)?'checked':''}>${l}</label>`).join('')}</div></fieldset><div class="form-grid">${field('毛利率目标下限（%）',input('margin_floor',c.margin_floor==null?'':c.margin_floor*100,'type="number" step="any" min="-100" max="100"'))}${field('经营现金收入比下限（%）',input('cash_floor',c.cash_floor==null?'':c.cash_floor*100,'type="number" step="any" min="-500" max="500"'))}${field('资产负债率上限（%）',input('leverage_ceiling',c.leverage_ceiling==null?'':c.leverage_ceiling*100,'type="number" step="any" min="0" max="500"'))}${field('数据更新提醒间隔（天）',input('stale_after_days',c.stale_after_days??180,'type="number" min="30" max="730" required'))}</div>${formFooter('保存企业目标')}</form>`:empty('还没有企业研究目标','导入真实数据后，可以分别配置不同企业的关注点。',routeButton('添加数据','data'))}</section>
 <section class="panel"><h2>外部服务与权限</h2><p class="muted">密钥只在服务器环境配置，不发送到前端。每次外部模型任务仍需逐次授权。</p>${table(['服务','运行状态'],state.caps.providers.map((v:Json)=>[esc(v.name??v.id),badge(v.configured?'已配置，需实际验证':'未配置',v.configured?'good':'neutral')]))}${notice('已配置不等于已验证。模型与搜索真实连通需要你的有效账户、额度和网络。')}<details><summary>查看服务能力与资源限制</summary>${jsonView(state.caps)}</details></section>
 <section class="panel"><h2>账户与数据</h2><p class="muted">${esc(state.user.email)} · 数据导出包含历史快照与个人记忆，请妥善保存。</p><div class="stack"><a class="secondary" href="/api/workspace/export" download>${icon('download')} 导出完整个人工作区</a>${button('清理计划、实验与行动记录','archive-dialog')}${button('修改登录密码','password-dialog')}${button('删除账户与全部数据','delete-account-dialog','text-button danger-text')}</div></section></div>`;
}
export async function opsPage(){const [runs,conversations,health]=await Promise.all([api('/runs'),api('/conversations'),api('/health')]);state.cache.runs=runs.items;state.cache.conversations=conversations.items;
 return heading('执行记录','没有隐藏操作：任务状态、输入快照、工具产物和错误都来自持久记录。',button(icon('refresh')+' 刷新状态','refresh'))+`<div class="runtime-strip"><span class="status-dot"></span><strong>服务已响应</strong><span>数据库可读</span><span>单进程执行</span><span>${timeText(health.time)}</span></div><section class="panel flush">${runs.items.length?table(['任务','状态','创建时间',''],runs.items.map((r:Json)=>[`<button class="title-button" data-route="agents:run-${esc(r.id)}"><span><strong>${esc(r.payload.query)}</strong><small>${esc(r.error??r.id)}</small></span></button>`,status(r.state),timeText(r.created_at),['queued','running'].includes(r.state)?button('取消','cancel-run','text-button',`data-id="${esc(r.id)}"`):routeButton('查看轨迹','agents:run-'+r.id)])):empty('尚无执行记录','任务开始后，每个已执行或跳过节点都会留下记录。',routeButton('创建研判计划','agents','primary'))}${runs.has_more?notice('当前显示最近 200 条；完整记录可从个人工作区导出。'):''}</section><section class="panel"><h2>会话管理</h2><p class="muted">删除会话同时删除关联报告、消息和执行记录；独立计划、行动与实验中的快照保留，可在设置中分别清理。</p>${conversations.items.length?table(['会话','企业','操作'],conversations.items.map((r:Json)=>[esc(r.payload.title),esc(r.payload.company),button(icon('trash')+' 删除会话','delete-conversation','text-button danger-text',`data-id="${esc(r.id)}"`)])):'<p class="muted">暂无会话。</p>'}</section>`;
}
