import {adaptiveOptions,graphCanvas,runtimeRibbon,adaptiveReport,runNeedsReconcile} from './views-orchestrator.js';
import {viewApi as api,viewWorkspace as workspace,type Json} from './api.js';
import {state,activeDataset,scopedDatasets,activeIdentity,scopeQuery} from './state.js';
import {esc,num,pct,amount,unitName,icon,button,routeButton,badge,status,notice,empty,heading,field,input,textarea,select,formFooter,jsonView,table,metricNames,metricValue,safeLink,timeText,citationCard,nodeFlow,lineChart} from './components.js';
import {qualityPanel} from './views-data.js';
export const modeNames={operational:'经营全景',margin:'毛利承压',industry:'行业证据',investment:'投资研究',deep_dive:'专项核查'};
export function datasetOptions(){return scopedDatasets().map(d=>({value:d.id,label:d.payload.company+' · '+d.payload.name}));}
export async function agentsPage(id=''){
 const [catalog,plans,templates,conversations]=await Promise.all([workspace('/orchestration/catalog'),workspace('/plans'+scopeQuery()),workspace('/templates'),api('/conversations')]);state.cache.audit=null;state.cache.agents=catalog.capabilities;state.cache.nodes=catalog.capabilities;state.cache.plans=plans.items;state.cache.templates=templates.items;
 if(id.startsWith('plan-'))return planPage(id.slice(5));
 if(id.startsWith('run-'))return runPage(id.slice(4));
 const identity=activeIdentity(),allowExternal=!identity||identity.payload.allow_external&&identity.payload.max_calls>0;const budget=identity?.payload.max_calls??3;
 const providers=catalog.providers.filter((p:Json)=>p.configured);const allProviderOpts=providers.map((p:Json)=>({value:p.id,label:p.id+' · '+p.model+(p.configured?'':'（未配置）')}));
 return heading('协同研判','从问题开始，先预览任务与授权范围，再执行。',button(icon('activity')+' 执行记录','go-ops'))+
 `<div class="studio-layout"><section class="panel"><div class="section-heading row-between"><h2>定义一次研判</h2>${badge('不会自动外发','good')}</div>${scopedDatasets().length?`<form id="plan-form" class="stack">${field('使用的数据集',select('dataset_id',datasetOptions(),state.active))}${field('你要解决什么问题？',textarea('query',state.query,'required minlength="5" maxlength="3000" rows="4" placeholder="写明需要作出的判断、关心的变化和希望拿到的结果"'))}<div class="quick-tasks">${['核查毛利变化与现金回流，列出依据和反向解释','识别经营数据缺口并制定资料补充清单','对照支持与反向证据，审查结论适用边界'].map(q=>button(esc(q),'fill-query','task-chip',`data-query="${esc(q)}"`)).join('')}</div><div class="form-grid">${field('研究方向',select('mode',modeNames,'operational'))}${field('比较基期',select('comparison',{year_over_year:'上年同季',previous:'上一季度'}))}</div>${field('验收标准',textarea('success_criteria','','rows="2" maxlength="1000" placeholder="例如：每个判断都提供对应指标、证据、替代解释和待核验项"'))}
 <div class="subpanel"><div class="row-between"><h3>${icon('spark')} 专家解释</h3><label class="switch-label"><input name="use_llm" id="use-llm" type="checkbox" ${allowExternal?'':'disabled'}> 启用外部模型</label></div><div class="form-grid model-options" id="model-options" hidden>${field('选择服务端已配置模型',select('provider',allProviderOpts,providers[0]?.id??''))}${field('单次调用上限',select('max_calls',Array.from({length:Math.max(1,budget)},(_,n)=>({value:String(n+1),label:'累计最多 '+(n+1)+' 次'})),String(Math.max(1,Math.min(3,budget)))))}</div><p class="micro">${!allowExternal?'当前身份只使用本地工具。可在身份设置中调整外部调用权限与预算。':providers.length?`${providers.length} 个模型已配置；连通性将在实际调用中记录。`:'没有配置模型时可完整执行数据核验、量化计算、证据检索和报告；不会伪造专家回答。'}</p><label class="check-label"><input name="include_memory" type="checkbox" checked> 纳入匹配且已批准的记忆</label><details><summary>延续既有会话（可选）</summary>${field('选择当前账户会话',select('session_id',[{value:'',label:'新建独立会话'},...conversations.items.filter((c:Json)=>(c.payload.identity_id??'')===state.identity&&(!c.payload.company||c.payload.company===activeDataset()?.payload.company)).map((c:Json)=>({value:c.id,label:c.payload.title}))]))}<label class="check-label"><input type="checkbox" name="include_history">明确纳入该会话的有限历史</label><p class="micro">默认不携带历史；已选内容与字符预算会在计划中显示。历史解释不视为新证据。</p></details></div>${adaptiveOptions(catalog,identity?.payload.depth??'balanced')}${formFooter('生成可审阅的执行计划')}</form>`:empty('先准备经营数据','Agent 的定量判断必须有明确输入，不能凭空生成企业状态。',routeButton('添加经营数据','data','primary'))}</section>
 <aside class="studio-side"><section class="panel"><div class="section-heading row-between"><h2>当前范围计划</h2><span class="micro">${plans.total} 份</span></div>${plans.items.length?plans.items.slice(0,6).map((p:Json)=>`<button class="list-link" data-route="agents:plan-${esc(p.id)}"><span>${status(p.payload.status)}<strong>${esc(p.payload.request.query)}</strong><small>${timeText(p.created_at)}</small></span>${icon('chevron')}</button>`).join(''):empty('尚无计划','生成计划不会消耗模型调用。')}</section>
 <section class="panel"><div class="section-heading row-between"><h2>任务模板</h2>${button(icon('plus'),'save-template-dialog','icon-button','aria-label="新建任务模板"')}</div>${templates.items.length?templates.items.map((t:Json)=>`<div class="row-between template-row">${button(esc(t.payload.name),'apply-template','text-button',`data-id="${esc(t.id)}"`)}${button(icon('trash'),'delete-template','icon-button',`data-id="${esc(t.id)}" data-version="${t.version}" aria-label="删除模板"`)}</div>`).join(''):'<p class="muted">将常用研究目标保存为模板，复用问题而不是旧数据。</p>'}</section></aside></div>`;
}
export async function planPage(id:string){const p=await workspace('/plans/'+id);state.cache.plan=p;state.cache.audit=null;state.cache.nodes=p.payload.nodes;const d=p.payload;
 return heading('确认执行计划',d.request.query,routeButton('返回工作台','agents','secondary'))+
 `<div class="plan-top"><span>${status(d.status)}</span><span>${esc(d.snapshot.dataset.company)} · ${esc(d.snapshot.dataset.periods.at(-1).period)}</span><span>${d.snapshot.citations.length} 条证据片段</span><span>${d.max_calls} 次模型调用上限</span></div>
 <div class="studio-layout"><section class="stack"><div class="panel"><div class="section-heading row-between"><h2>执行分工</h2><span class="micro">实线职责 · 按依赖执行</span></div>${d.adaptive?graphCanvas(d.nodes):nodeFlow(d.nodes)}${d.adaptive?`<details><summary>为什么这样编排 · 已批准的自适应范围</summary><p class="micro">模型可在列明的只读能力、角色与累计预算内调整分工；同一输入快照的工具产物可作为后续专家上下文。实际外发字符与产物散列会逐次记录。</p>${jsonView({decisions:d.adaptive.decisions,envelope:d.adaptive.envelope,roles:d.adaptive.provider_bindings,fallbacks:d.adaptive.fallback_bindings})}</details>`:''}<p class="micro">点击节点查看职责、工具权限和依赖。灰色节点不执行，也不计作模型调用。</p></div>
 <div class="panel"><div class="section-heading"><h2>本次输入边界</h2></div>${qualityPanel(d.quality)}<details><summary>已选证据 · ${d.snapshot.citations.length} 条</summary>${d.snapshot.citations.map(citationCard).join('')||'<p class="muted">未检索到匹配证据，相关事实保持缺失。</p>'}</details><details><summary>已选记忆 · ${d.snapshot.memory.length} 条</summary>${d.snapshot.memory.map((m:Json)=>`<p>${esc(m.text)} ${badge(!d.max_calls?'本地快照，不外发':d.packing.included_memory_ids.includes(m.id)?'将发送':'预算排除')}</p>`).join('')||'<p class="muted">没有可召回的已批准记忆。</p>'}${d.excluded_memory.length?jsonView(d.excluded_memory):''}</details><details><summary>查看完整上下文与外发范围</summary>${jsonView(d.context)}</details></div></section>
 <aside class="stack"><section class="panel approval"><span class="eyebrow">执行授权</span><h2>${d.max_calls?'外部专家参与':'本地工具执行'}</h2><dl class="definition-list"><div><dt>上下文</dt><dd>${num(d.packing.characters,0)} 字符</dd></div><div><dt>总字符预算</dt><dd>${num(d.packing.limit,0)}</dd></div><div><dt>模型调用</dt><dd>最多 ${d.max_calls} 次</dd></div><div><dt>写入权限</dt><dd>模型无写库/交易权限</dd></div></dl>${d.packing.dropped.length?notice(`预算排除了 ${d.packing.dropped.length} 个完整条目；不会静默截断标识。`):''}${d.blockers.map((b:string)=>notice(b,'danger')).join('')}
 ${d.status==='draft'?`<form id="execute-plan-form" data-id="${esc(id)}" class="stack">${d.max_calls?`<label class="check-label consent"><input type="checkbox" name="external_consent" required> 我已核对上下文，同意将上述范围的数据发送给计划列明的模型；仅在我选择的候补范围与累计预算内降级。</label>`:'<p class="micro">本计划不会调用外部模型或自动搜索网络。</p>'}${formFooter('批准并执行')}${button('取消此计划','cancel-plan','text-button',`data-id="${esc(id)}" data-version="${p.version}"`)}</form>`:d.run_id?routeButton('查看执行与报告 '+icon('arrow'),'agents:run-'+d.run_id,'primary'):notice('此计划已取消，没有外部调用。')}
 </section><details class="panel"><summary>计划指纹与绑定</summary><p class="micro">修改数据、审阅、记忆或偏好后，旧计划需重建。</p><code>${esc(d.fingerprint)}</code>${jsonView(d.bindings)}</details></aside></div>`;
}
export async function runPage(id:string){
 let [run,audit,reviews]=await Promise.all([api('/runs/'+id),workspace('/runs/'+id+'/audit'),workspace('/runs/'+id+'/reviews')]);state.cache.run=run;state.cache.audit=audit;state.cache.reviews=reviews.items;
 const plan=run.snapshot.studio;const runtime=plan?.adaptive?await workspace('/runs/'+id+'/runtime'):null;
 if(runNeedsReconcile(run,runtime)){[run,audit]=await Promise.all([api('/runs/'+id),workspace('/runs/'+id+'/audit')]);state.cache.run=run;state.cache.audit=audit;}
 state.cache.runtime=runtime;const nodes=runtime?.graph.payload.nodes??plan?.nodes??state.cache.agents??[];state.cache.nodes=nodes;
 const complete=!['queued','running'].includes(run.state),r=run.result;
 const head=heading(r?.title??'执行中的研判',run.payload.query,routeButton('新建研判','agents','secondary')+(r?`<a class="secondary" href="/api/runs/${esc(id)}/export?format=md" download>${icon('download')} 导出报告</a> <a class="secondary" href="/api/runs/${esc(id)}/export?format=json" download>完整 JSON</a>`:''));
 return head+(runtime?`<div id="runtime-ribbon">${runtimeRibbon(runtime)}</div>`:'')+`<div class="run-strip" id="run-strip">${status(run.state)}<span>${esc(run.snapshot.dataset.company)}</span><span>开始 ${timeText(run.created_at)}</span>${run.state==='running'||run.state==='queued'?button('取消执行','cancel-run','text-button danger-text',`data-id="${esc(id)}"`):''}${badge(audit.ledger.valid&&audit.data_hash_valid&&audit.snapshot_hash_valid!==false&&audit.report_hash_valid!==false&&audit.artifacts.every((a:Json)=>a.integrity_valid&&a.event_anchor_valid)?'记录一致性通过':'记录一致性异常',audit.ledger.valid&&audit.data_hash_valid&&audit.snapshot_hash_valid!==false&&audit.report_hash_valid!==false&&audit.artifacts.every((a:Json)=>a.integrity_valid&&a.event_anchor_valid)?'good':'danger')}</div>
 <div class="tabs" role="tablist" aria-label="研判结果标签"><button role="tab" aria-selected="true" class="active" data-action="run-tab" data-tab="summary">结果摘要</button><button role="tab" aria-selected="false" data-action="run-tab" data-tab="agents">Agent 执行链</button><button role="tab" aria-selected="false" data-action="run-tab" data-tab="sources">证据与上下文</button><button role="tab" aria-selected="false" data-action="run-tab" data-tab="rules">计算与血缘</button></div>
 <div id="run-tab-summary" class="run-tab">${r?reportSummary(run,reviews.items)+adaptiveReport(r):`<section class="panel">${complete?notice(run.error??'任务未产生报告，未伪造完成内容。','warm'):notice('任务状态来自服务端持久记录。完成后显示报告，关闭页面不会伪造或抹除执行。')}${runtime?`<div data-live-graph>${graphCanvas(nodes,audit.trace,runtime.state)}</div>`:nodeFlow(nodes,audit.trace,run.state)}<div id="live-run-status" aria-live="polite">${complete?'':`<p class="muted">正在等待真实执行结果…</p>`}</div></section>`}</div>
 <div id="run-tab-agents" class="run-tab" hidden><section class="panel"><div class="section-heading row-between"><h2>协同执行轨迹</h2>${button('导出审计数据','export-audit')}</div>${runtime?`<div data-live-graph>${graphCanvas(nodes,audit.trace,runtime.state)}</div>`:nodeFlow(nodes,audit.trace,run.state)}${table(['时间','事件','节点 / 内容'],audit.trace.map((e:Json)=>[timeText(e.created_at),esc(e.type),`${esc(e.payload.node??e.payload.agent??'')}${e.payload.duration_ms!==undefined?' · '+num(e.payload.duration_ms)+' ms':''}${e.payload.reason?'<p class="micro">'+esc(e.payload.reason)+'</p>':''}`]))}<details><summary>数据与事件完整性</summary>${jsonView({ledger:audit.ledger,data_hash_valid:audit.data_hash_valid,snapshot_hash_valid:audit.snapshot_hash_valid,report_hash_valid:audit.report_hash_valid,artifacts:audit.artifacts.map((a:Json)=>({node:a.node,integrity:a.integrity_valid,event_anchor:a.event_anchor_valid}))})}</details></section></div>
 <div id="run-tab-sources" class="run-tab" hidden><section class="panel"><h2>冻结证据与上下文</h2>${run.snapshot.citations.length?run.snapshot.citations.map(citationCard).join(''):empty('本次没有匹配证据','无来源的事实不因模型输出而变得可信。')}<details><summary>实际发送与选中记忆</summary>${jsonView({selected:run.snapshot.memory,actually_sent:r?.memory_used??null,packing:plan?.packing??null})}</details><details><summary>完整任务快照（包含个人业务数据）</summary>${jsonView(run.snapshot)}</details></section></div>
 <div id="run-tab-rules" class="run-tab" hidden>${r?rulesView(r):notice('计算结果尚未保存。')}</div>`;
}
function reportSummary(run:Json,reviews:Json[]){const r=run.result,a=r.analysis,m=a.metrics,unit=state.user.preferences.amount_unit;const profile=run.snapshot.profile;
 return `<div class="metric-row">${['gross_margin','cash_ratio','leverage'].map(k=>`<article class="metric"><div class="metric-label">${metricNames[k]}</div><strong>${pct(m[k])}</strong><small>${esc(a.current_period)} · 来源于本次数据快照</small></article>`).join('')}</div><div class="two-columns"><section class="panel"><div class="section-heading row-between"><h2>可核验的计算结论</h2>${badge('确定性计算','good')}</div>${r.findings.map((f:string)=>`<p class="finding">${esc(f)}</p>`).join('')}<details><summary>数据与方法限制 · ${r.warnings.length} 项</summary>${r.warnings.map((w:string)=>`<p class="micro">${esc(w)}</p>`).join('')}</details><div class="section-heading row-between"><h3>模型解释</h3>${status(r.llm.state)}</div>${r.llm.review.claims.length?r.llm.review.claims.map((c:Json)=>{const rev=reviews.find(v=>v.payload.claim_id===c.id);return `<article class="claim"><p>${esc(c.text)}</p><div class="tag-row">${(c.metric_ids??[]).map((k:string)=>badge((metricNames[k]??k)+' '+metricValue(k,m[k]))).join('')}${(c.citation_ids??[]).map(()=>badge('已关联证据')).join('')}</div><div class="row-between"><small>${rev?'人工审阅：'+esc(rev.payload.verdict):'尚待人工复核；结构检验不等于事实证明'}</small>${button('审阅解释','review-claim','text-button',`data-id="${esc(c.id)}"`)}</div></article>`}).join(''):notice(r.llm.state==='not_requested'?'本次未授权模型解释。定量分析、证据与执行记录已保留。':'未产生通过结构门禁的模型解释；不会用模板代替模型响应。')}${r.llm.review.rejected_claims?notice(`${r.llm.review.rejected_claims} 条模型输出未通过引用/格式门禁，未作为结论显示。`,'warm'):''}</section>
 <section class="stack"><div class="panel"><div class="section-heading"><h2>经营变化</h2></div>${lineChart(a.series,[{id:'revenue',name:'营业收入'},{id:'cost',name:'营业成本'}],unitName(unit),({yuan:1,wan:1e4,yi:1e8} as Record<string,number>)[unit]??1e4)}</div><div class="panel"><span class="eyebrow">转为可执行事项</span><h3>让判断有后续</h3><p class="muted">创建负责人、验收标准与截止日期，完成时记录证据和验收结果。</p>${button('创建跟进行动 '+icon('arrow'),'action-from-report','primary')}${r.missing?.length?`<ul class="compact-list">${r.missing.map((s:string)=>`<li>${esc(s)}</li>`).join('')}</ul>`:''}${profile?.objective?`<p class="micro">本次研究目标：${esc(profile.objective)}</p>`:''}</div></section></div>`;
}
export function rulesView(r:Json){const a=r.analysis;return `<section class="panel"><h2>指标血缘</h2><p class="muted">原始字段 → 计算公式 → 指标值。点击单项可展开完整输入。</p>${(r.lineage??[]).map((l:Json)=>`<details><summary><span>${esc(l.label)}</span><strong>${metricValue(l.id,l.value)}</strong></summary><p><code>${esc(l.formula)}</code></p>${table(['字段路径','原始值','单位'],l.inputs.map((v:Json)=>[esc(v.path),num(v.value),esc(v.unit)]))}</details>`).join('')||jsonView(a.metrics)}<h2 class="section-heading">规则指数贡献</h2>${notice('GMPS / DQI 是未经经验校准的研究规则，不是风险概率。缺失覆盖率和原始阈值独立披露。')}${['gmps','dqi'].map(kind=>{const obj=a[kind];return `<details><summary><span>${kind.toUpperCase()} · ${esc(obj.method)}</span>${num(obj.score)} / 覆盖 ${pct(obj.coverage)}</summary>${table(['维度','观测 / 变化','规则分','权重','公式'],obj.dimensions.map((d:Json)=>[esc(d.label),num(d.value??d.change,4),num(d.score),pct(d.weight),esc(d.formula)]))}</details>`}).join('')}</section>`;}
export function templateForm(){return `<form id="template-form" class="stack">${field('模板名称',input('name','','required maxlength="200"'))}${field('研究问题',textarea('query',state.query,'rows="4" minlength="5" required'))}${field('研究方向',select('mode',modeNames))}${field('验收标准',textarea('success_criteria','','rows="2"'))}${formFooter('保存模板')}</form>`;}
