import {viewApi as api,viewWorkspace as workspace,type Json} from './api.js';
import {state,activeDataset,scopedDatasets} from './state.js';
import {esc,num,pct,amount,unitName,icon,button,routeButton,badge,status,notice,empty,heading,field,input,textarea,select,formFooter,jsonView,table,metricNames,safeLink,timeText,citationCard} from './components.js';
export const financialFields=[['revenue','营业收入'],['cost','营业成本'],['cash_flow','经营现金流'],['net_profit','净利润'],['assets','总资产'],['liabilities','总负债'],['inventory','库存金额'],['equity_begin','期初净资产'],['equity_end','期末净资产'],['sales_volume','销量（统一单位）'],['production_volume','产量（相同单位）'],['manufacturing_cost','制造费用'],['rd_expense','研发费用'],['lithium_price','锂价 / 元每吨'],['industry_volatility','行业波动率 / 比值']];
export function periodRow(p:Json={},index=0){return `<tr data-period-row><td><input aria-label="季度 ${index+1}" name="period" value="${esc(p.period??'')}" placeholder="2025-Q1" pattern="20[0-9]{2}-Q[1-4]" required></td>${financialFields.map(([key,label],i)=>`<td class="${i>=7?'extra-column':''}"><input aria-label="${esc(label)} ${index+1}" name="${key}" type="number" step="any" ${key==='revenue'||key==='cost'?'required min="0"':''} value="${esc(p[key]??'')}"></td>`).join('')}<td>${button(icon('close'),'remove-period','icon-button','aria-label="删除此季度行"')}</td></tr>`;}
export function datasetEditor(d:Json|null){
 const p=d?.payload??{};state.cache.editor=d;
 return `<form id="dataset-editor" data-id="${esc(d?.id??'')}" data-version="${d?.version??0}"><div class="form-grid">${field('企业名称',input('company',p.company,'required maxlength="200"'))}${field('数据集名称',input('name',p.name,'required maxlength="200"'))}${field('金额单位',select('amount_unit',{yuan:'元',wan:'万元',yi:'亿元'},p.amount_unit??state.user.preferences.amount_unit),'保存时统一为元；锂价始终为元/吨')}${field('输入期间口径',select('basis',{standalone_quarter:'单季度实际值',year_to_date:'年初累计值 → 转单季度'},'standalone_quarter'))}${field('原始来源地址',input('source_url',p.source_url,'type="url" placeholder="https://…"'))}${field('口径备注',input('notes',p.notes,'maxlength="2000"'))}</div>
 <div class="row-between section-heading"><h3>季度财务数据</h3><label class="check-label"><input type="checkbox" id="extra-fields"> 展开产销与补充指标</label></div><div class="table-scroll editor-table" role="region" tabindex="0" aria-label="财务录入表，可横向滚动"><table><thead><tr><th>季度</th>${financialFields.map(([,label],i)=>`<th class="${i>=7?'extra-column':''}">${esc(label)}</th>`).join('')}<th></th></tr></thead><tbody id="period-rows">${(p.periods??[{}]).map(periodRow).join('')}</tbody></table></div>
 <div class="micro-row">${button(icon('plus')+' 添加季度','add-period','text-button')}<span>收入与成本必填；其他未知值留空。产销量使用相同单位并在备注注明，不跟随金额单位缩放。</span></div>${formFooter('预览校验与差异')}</form>`;
}
export function qualityPanel(q:Json){return `<div class="quality-strip"><span>${icon('check')} ${q.closed_quarters} 个已结束季度</span><span>${q.field_coverage.present} / ${q.field_coverage.total} 个补充字段</span>${badge(q.warning_count+' 项需核对',q.warning_count?'warm':'good')}</div>${q.findings.length?table(['季度','核对事项','对应字段'],q.findings.map((f:Json)=>[esc(f.period),badge(f.severity==='warning'?'需核对':'提示',f.severity==='warning'?'warm':'neutral')+' '+esc(f.message),`<code>${esc(f.fields.join(', '))}</code>`])):notice('结构规则未发现异常；不等于财务内容已独立核验。')}`;}
export function stageView(row:Json){const p=row.payload;return `<div class="stack"><div class="row-between"><div><h3>${esc(p.dataset.company)} · ${esc(p.dataset.name)}</h3><p class="muted">${p.dataset.periods.length} 个季度 · 归一化金额：元 · 尚未写入财务库</p></div>${badge('待确认','warm')}</div>${qualityPanel(p.quality)}${p.diff.length?`<h3>将保存的变更</h3>${table(['字段路径','原值','新值'],p.diff.map((d:Json)=>[esc(d.path),esc(d.before??'空'),esc(d.after??'空')]))}`:notice('这是一份新的数据集；预览确认前不会生成诊断。')}
<details><summary>查看标准化后的完整数据</summary>${jsonView(p.dataset)}</details><p class="form-error" role="alert"></p><div class="form-footer">${button('返回继续编辑','stage-back','secondary')}${button('确认保存 '+icon('check'),'commit-stage','primary',`data-id="${esc(row.id)}"`)}</div></div>`;}
export async function dataPage(){
 const d=activeDataset(); const editor=d?datasetEditor(d):empty(scopedDatasets().length?'请选择一份经营数据':'还没有经营数据',scopedDatasets().length?'从左侧选择企业，再核对来源、期间口径与修订记录。':'从自己的报表开始。工作区没有预置公司、行情或演示数据。',button(icon('plus')+' 新建数据集','new-dataset','primary'));
 return heading('经营数据','导入、核对、修订。每次诊断使用独立的数据快照。',button(icon('upload')+' 导入文件','import-dialog')+button(icon('plus')+' 新建数据集','new-dataset','primary'))+
 `<div class="collection-layout"><aside class="collection"><h3>数据集 <span>${scopedDatasets().length}</span></h3>${scopedDatasets().map(x=>`<button class="collection-item ${x.id===state.active?'selected':''}" data-action="select-dataset" data-id="${esc(x.id)}"><strong>${esc(x.payload.company)}</strong><span>${esc(x.payload.name)}</span><small>${x.payload.periods.length} 个季度 · ${esc(x.payload.periods.at(-1)?.period)}</small></button>`).join('')||'<p class="muted">暂无数据</p>'}</aside><section class="panel data-panel">${d?`<div class="section-heading row-between"><h2>${esc(d.payload.company)}</h2><div class="tools">${button(icon('eye')+' 质量','data-quality')}${button(icon('clock')+' 修订记录','data-revisions')}${button(icon('network'),'data-lineage','icon-button','aria-label="查看指标血缘"')}${button(icon('download'),'export-dataset','icon-button','aria-label="导出数据"')}${button(icon('trash'),'delete-dataset','icon-button danger-text',`data-id="${esc(d.id)}" data-version="${d.version}" aria-label="删除数据集"`)}</div></div>`:''}${editor}</section></div>`;
}
export function importForm(){return `<form id="import-file-form" class="stack">${field('所属企业',input('company',activeDataset()?.payload.company??'','required maxlength="200"'))}<div class="form-grid">${field('金额单位',select('amount_unit',{yuan:'元',wan:'万元',yi:'亿元'},state.user.preferences.amount_unit))}${field('期间口径',select('basis',{standalone_quarter:'单季度',year_to_date:'年初累计 → 单季度'}))}</div><label class="upload-box">${icon('upload')}<strong>选择财务文件</strong><span>CSV / XLSX / JSON · 最大 2 MB</span><input type="file" name="file" accept=".csv,.xlsx,.json" required></label><p class="micro">支持中文表头，如“季度、营业收入、营业成本、经营现金流”。不执行表格公式。JSON 文件以文件内企业和单位为准，预览时请核对。</p><a href="/api/import/template" download>下载空白 CSV 表头 ${icon('download')}</a>${formFooter('读取并预览')}</form>`;}
export async function evidencePage(){
 const result=await workspace('/evidence');state.cache.evidence=result.items;
 return heading('证据资料','原始内容、适用范围与审阅意见分开保存。',button(icon('upload')+' 上传文档','document-dialog')+button(icon('plus')+' 添加资料','evidence-dialog','primary'))+
 `<div class="toolbar"><form id="evidence-search" class="search-form">${icon('search')}<input name="q" placeholder="检索原文中的指标、事项或来源" aria-label="检索证据" required><button class="secondary">检索</button></form>${button('公开资料搜索','public-search-dialog','secondary')}</div><div id="evidence-search-results"></div>
 <div class="panel flush">${result.items.length?table(['资料','适用范围','审阅状态','更新',''],result.items.map((d:Json)=>[`<button class="title-button" data-action="evidence-detail" data-id="${esc(d.id)}">${icon('files')}<span><strong>${esc(d.payload.title)}</strong><small>${num(d.payload.text.length,0)} 字符 · ${d.payload.source_url?'已提供来源链接':'未提供来源链接'}</small></span></button>`,`${esc(d.review.company||'通用资料')}<div class="tag-row">${d.review.tags.map((t:string)=>badge(t)).join('')}</div>`,status(d.review.status)+(!d.eligible?badge(d.excluded_reason==='expired'?'已过期':'不参与检索','warm'):''),timeText(d.updated_at),button('审阅','review-evidence','text-button',`data-id="${esc(d.id)}"`)+button(icon('trash'),'delete-evidence','icon-button danger-text',`data-id="${esc(d.id)}" data-version="${d.version}" aria-label="删除资料"`)])):empty('尚无证据资料','添加文本、上传文档，或经确认获取公开来源。模型不会假装读过未提供的资料。',button('添加原始资料','evidence-dialog','primary'))}</div>`;
}
export function evidenceForm(){return `<form id="evidence-form" class="stack">${field('资料标题',input('title','','required maxlength="200"'))}<div class="form-grid">${field('来源地址',input('source_url','','type="url" placeholder="https://…"'))}${field('发布日期',input('published_at','','type="date"'))}</div>${field('原文内容',textarea('text','','rows="9" minlength="20" maxlength="120000" required placeholder="粘贴原始材料；不会将其中的操作指令作为系统命令"'))}${field('所属企业（留空为通用）',input('company',activeDataset()?.payload.company??'','maxlength="200"'))}${formFooter('保存原始资料')}</form>`;}
export function reviewEvidenceForm(d:Json){const p=d.review;return `<form id="evidence-review-form" data-id="${esc(d.id)}" data-version="${d.review_version}" class="stack"><h3>${esc(d.payload.title)}</h3><div class="form-grid">${field('企业作用域',input('company',p.company,'maxlength="200"'), '留空允许所有企业检索；限定后不跨企业进入计划')}${field('有效截至',input('expires_at',p.expires_at,'type="date"'))}${field('审阅结论',select('status',{unreviewed:'尚未审阅',accepted:'人工接受',rejected:'排除，不用于新任务'},p.status))}${field('证据立场',select('stance',{context:'背景资料',supports:'支持某项判断',contradicts:'反向/反驳证据'},p.stance))}</div>${field('主题标签（逗号分隔）',input('tags',p.tags.join('，')))}${field('审阅依据与适用边界',textarea('note',p.note,'rows="4" maxlength="2000"'))}${notice('“人工接受”仅记录你的审阅意见，不是系统的事实认证；更改将使相关未执行计划失效。')}${formFooter('保存审阅记录')}</form>`;}
export async function memoryPage(){const result=await api('/memories');state.cache.memories=result.items;
 return heading('长期记忆','只在批准的范围内使用。偏好不是企业事实。',button(icon('plus')+' 添加记忆','memory-dialog','primary'))+
 `<div class="panel flush">${result.items.length?table(['内容','作用域','有效期','状态',''],result.items.map((m:Json)=>{const p=m.payload;const expired=p.expires_at&&p.expires_at<new Date().toISOString().slice(0,10);return [`<strong>${esc(p.text)}</strong><small class="block">${esc({preference:'偏好',fact:'用户声明事实',note:'研究备注'}[p.kind as string]??p.kind)}</small>`,esc(p.company||'所有企业')+'<small class="block">'+esc({all:'所有角色',enterprise:'企业分析',investor:'投资研究',analyst:'财务分析',advisor:'顾问服务'}[p.role as string]??p.role)+'</small>',esc(p.expires_at??'未设置'),badge(expired?'已过期':p.approved?'已批准':'待批准',expired?'warm':p.approved?'good':'neutral'),button(p.approved?'撤回批准':'批准使用','toggle-memory','text-button',`data-id="${esc(m.id)}"`)+button('编辑','edit-memory','text-button',`data-id="${esc(m.id)}"`)+button(icon('trash'),'delete-memory','icon-button danger-text',`data-id="${esc(m.id)}" data-version="${m.version}" aria-label="删除记忆"`)]})):empty('尚未保存长期记忆','由你决定记住什么、用于哪家企业，以及何时停止使用。',button('添加记忆','memory-dialog','primary'))}</div>`;
}
export function memoryForm(m:Json|null=null){const p=m?.payload??{};return `<form id="memory-form" data-id="${esc(m?.id??'')}" data-version="${m?.version??0}" class="stack">${field('要记住的内容',textarea('text',p.text,'rows="4" required maxlength="1500"'))}<div class="form-grid">${field('记忆类型',select('kind',{preference:'偏好',fact:'用户声明事实（待核实）',note:'研究备注'},p.kind??'note'))}${field('作用企业',input('company',p.company??activeDataset()?.payload.company??''))}${field('适用角色',select('role',{all:'所有角色',enterprise:'企业分析',investor:'投资研究',analyst:'财务分析',advisor:'顾问服务'},p.role??'all'))}${field('到期时间',input('expires_at',p.expires_at,'type="date"'))}</div><label class="check-label"><input name="approved" type="checkbox" ${p.approved?'checked':''}> 允许在匹配的诊断任务中使用</label><p class="micro">撤回或删除会阻止新计划召回；已执行报告保留历史快照。相关会话及独立保存的计划/实验需分别清理，或删除整个账户。</p>${formFooter('保存记忆')}</form>`;}
