import {mathResult,reflectionView} from './math-results.js';
import {viewWorkspace as workspace,viewApi as api,type Json} from './api.js';
import {state} from './state.js';
import {esc,icon,button,routeButton,heading,field,select,input,textarea,formFooter,notice,badge,num,jsonView,table,timeText,empty,nodeFlow} from './components.js';

export function graphLayout(nodes:Json[]){
  const ids=new Set(nodes.map(n=>n.id));const remaining=new Map(nodes.map(n=>[n.id,new Set<string>(n.depends_on??[])]));const layers:string[][]=[];
  if(ids.size!==nodes.length||nodes.some(n=>(n.depends_on??[]).some((d:string)=>!ids.has(d))))throw new Error('执行图包含重复节点或缺失依赖');
  while(remaining.size){const ready=[...remaining].filter(([,deps])=>deps.size===0).map(([id])=>id);if(!ready.length)throw new Error('执行图含循环依赖');layers.push(ready);ready.forEach(id=>remaining.delete(id));remaining.forEach(deps=>ready.forEach(id=>deps.delete(id)));}
  return layers;
}
function nodeState(n:Json,trace:Json[],overall:string){
  const e=trace.filter(e=>e.payload?.node===n.id&&['step_started','step_completed','step_skipped'].includes(e.type)).at(-1);
  if(e?.type==='step_completed')return ['failed','blocked','unknown','unavailable','missing','needs_input'].includes(e.payload.outcome)?'attention':'done';
  if(e?.type==='step_skipped'||n.enabled===false)return 'skipped';
  if(e?.type==='step_started')return ['running','queued','pause_requested'].includes(overall)?'running':'attention';
  return ['succeeded','degraded','failed','cancelled','interrupted'].includes(overall)?'unreached':'waiting';
}
export function graphCanvas(nodes:Json[],trace:Json[]=[],overall='draft'){
  let layers:string[][];try{layers=graphLayout(nodes);}catch(e){return notice('图结构异常，未显示伪造的执行链：'+String(e),'danger');}
  const width=Math.max(760,Math.max(0,...layers.map(l=>l.length))*192+30),nw=174,nh=58,gap=18,row=96;const pos=new Map<string,{x:number;y:number}>();
  layers.forEach((layer,i)=>layer.forEach((id,j)=>pos.set(id,{x:(width-(layer.length*nw+(layer.length-1)*gap))/2+j*(nw+gap),y:24+i*row})));
  const height=layers.length*row+14;const names={done:'已记录',running:'执行中',attention:'查看限制',waiting:'待执行',skipped:'不执行',unreached:'未到达'};
  const edges=nodes.flatMap(n=>(n.depends_on??[]).map((d:string)=>{const p=pos.get(d)!,q=pos.get(n.id)!;return `<path class="dag-edge" d="M${p.x+nw/2},${p.y+nh} C${p.x+nw/2},${p.y+nh+25} ${q.x+nw/2},${q.y-25} ${q.x+nw/2},${q.y}"/><circle class="dag-joint" cx="${q.x+nw/2}" cy="${q.y}" r="2"/>`;})).join('');
  const boxes=nodes.map(n=>{const p=pos.get(n.id)!,status=nodeState(n,trace,overall),name=n.name??n.id;return `<g class="dag-node ${status}" data-node="${esc(n.id)}" data-action="node-details" data-id="${esc(n.id)}" role="button" tabindex="0" aria-label="${esc(name+'，'+names[status]+'，查看职责与产物')}" transform="translate(${p.x},${p.y})"><rect class="dag-node-bg" width="${nw}" height="${nh}" rx="12"/><circle class="dag-indicator" cx="16" cy="19" r="3.5"/><text class="dag-label" x="28" y="23">${esc(name.slice(0,12))}</text><text class="dag-meta" x="15" y="44">${esc(n.engine==='optional_llm'?'模型专家':'本地工具')} · ${names[status]}</text></g>`;}).join('');
  return `<section class="graph-shell" aria-label="实际依赖图"><div class="graph-toolbar"><div class="graph-legend"><span><i></i> 工具 / 专家按依赖调度</span><span>${nodes.length} 个计划节点</span></div><div>${button('图 / 清单','graph-toggle','text-button')}${button('−','graph-minus','icon-button','aria-label="缩小执行图"')}${button('+','graph-plus','icon-button','aria-label="放大执行图"')}</div></div><div class="graph-scroll zoom-normal"><svg class="dag-svg" viewBox="0 0 ${width} ${height}" role="group" aria-label="工作流依赖图；节点可通过键盘选择">${edges}${boxes}</svg></div><div class="graph-list" hidden>${nodeFlow(nodes,trace,overall)}${table(['节点','前置依赖'],nodes.map(n=>[esc(n.name??n.id),esc((n.depends_on??[]).join('、')||'输入')]))}</div></section>`;
}
export function adaptiveOptions(catalog:Json,depth='balanced'){
  const providers=[{value:'',label:'沿用默认模型'},...catalog.providers.filter((p:Json)=>p.configured).map((p:Json)=>({value:p.id,label:p.id+(p.configured?'':' · 未配置')}))];
  return `<section class="autonomy-options"><div class="row-between"><h3>${icon('network')} 编排方式</h3>${badge('目标驱动','good')}</div><div class="form-grid">${field('研究深度',select('depth',{'':'遵循已激活策略（无策略时均衡）',concise:'聚焦 · 只做必要工作',balanced:'均衡 · 按目标与缺口编排',deep:'深入 · 增强反证与资料核查'},depth))}${field('最大并行工具数',select('parallelism',{'1':'1 · 顺序执行','2':'2 · 有界并行','3':'3 · 有界并行'},'2'))}</div><label class="check-label"><input type="checkbox" name="local_recovery" checked> 发现缺口时，自主追加已授权的只读核查步骤</label><label class="check-label"><input type="checkbox" name="forecast"> 将时间序列回测加入同一任务（样本不足不预测）</label><div class="form-grid">${field('回测目标',select('forecast_metric',{revenue:'营业收入',cost:'营业成本',cash_flow:'经营现金流',gross_margin:'毛利率'},'revenue'))}${field('预测步数',select('forecast_horizon',{'1':'1个季度','2':'2个季度','3':'3个季度','4':'4个季度'},'2'))}</div><details><summary>模型编排、修订与分工模型</summary><label class="check-label"><input type="checkbox" name="model_planning"> 外部模型参与后续任务分工（占用一次调用预算）</label><div class="form-grid">${field('结构错误的修订上限',select('max_revisions',{'0':'不修订','1':'最多1轮','2':'最多2轮'},'1'))}${field('累计外发字符预算',input('total_context_chars','72000','type="number" min="2000" max="144000" required'))}</div><div class="form-grid">${field('经营解释模型',select('route_analyst',providers))}${field('资料研究模型',select('route_researcher',providers))}${field('反证审阅模型',select('route_challenger',providers))}${field('规划模型',select('route_planner',providers))}${field('修订模型',select('route_revision',providers))}</div>${field('明确许可的候补模型',select('fallback_provider',[{value:'',label:'不跨模型降级'},...providers.filter(p=>p.value)]))}<p class="micro">只有明确的 HTTP 429 可使用授权候补；未知超时不自动重发。每次尝试都计入上限，候补调用可能计费。不同角色可选不同已配置模型。</p></details><details><summary>把明确情景假设交给建模工具</summary><label class="check-label"><input type="checkbox" name="with_scenario"> 启用本次情景建模，以下数值均为我确认的假设</label><div class="form-grid">${field('价格变化（%）',input('scenario_price','0','type="number" min="-80" max="100" step="0.1"'))}${field('单位变动成本变化（%）',input('scenario_cost','0','type="number" min="-80" max="100" step="0.1"'))}${field('销量变化（%）',input('scenario_volume','0','type="number" min="-80" max="100" step="0.1"'))}${field('固定成本比例（%）',input('scenario_fixed','0','type="number" min="0" max="100" step="0.1"'))}</div>${field('假设依据',textarea('scenario_note','','rows="2" maxlength="1000" placeholder="启用情景时必填；固定成本比例为假设，不是系统推断"'))}</details></section>`;
}
export function runtimeRibbon(runtime:Json){
  const u=runtime.usage,env=runtime.graph.payload.envelope,c=runtime.control;const live=['queued','running','pause_requested'].includes(runtime.state);
  return `<div class="runtime-cockpit"><div><span class="eyebrow">执行控制台</span><h3>${esc(({queued:'等待调度',running:'正在执行',paused:'已在安全边界暂停',pause_requested:'等待在途步骤结束',interrupted:'服务中断 · 可显式继续',succeeded:'执行已完成',degraded:'完成 · 有未满足条件',failed:'任务失败',cancelled:'已取消'} as Record<string,string>)[runtime.state]??runtime.state)}</h3></div><div class="runtime-counters"><span><strong>${u.attempts} / ${env.max_calls}</strong>调用尝试</span><span><strong>${num(u.characters,0)}</strong>累计外发字符</span><span><strong>${runtime.checkpoints.filter((x:Json)=>x.artifact_id).length}</strong>已保存断点</span></div><div class="runtime-actions">${live?button(runtime.state==='pause_requested'?'等待暂停':'安全暂停','pause-run','secondary',`data-id="${esc(c.run_id)}" ${runtime.state==='pause_requested'?'disabled':''}`):['paused','interrupted'].includes(runtime.state)?button('从断点继续','resume-run','primary',`data-id="${esc(c.run_id)}"`):''}${['paused','interrupted'].includes(runtime.state)?button('取消','cancel-run','text-button danger-text',`data-id="${esc(c.run_id)}"`):''}</div><p id="live-transport" class="micro" aria-live="polite">状态读取自服务端 · 断点复用不会重复已完成调用</p></div>`;
}
export function adaptiveReport(r:Json){
 if(!r?.adaptive)return '';
 const a=r.adaptive;return `<section class="panel adaptive-results"><div class="section-heading row-between"><h2>建模结果与执行复盘</h2>${button('反馈并建立验收案例','assessment-dialog','secondary')}</div>${Object.entries(a.mathematical_outputs??{}).map(([kind,value])=>mathResult(kind,value,state.user?.preferences?.amount_unit??'wan')).join('')}${reflectionView(a.reflection)}<p class="micro">以上值直接来自本次已保存产物，不随当前数据修订重新计算。自然语言验收标准仍须人工确认。</p></section>`;
}
export function assessmentForm(old:Json,context:Json={}){const p=old?.payload??{};return `<form id="assessment-form" class="stack" data-version="${old?.version??0}" data-review-context-hash="${esc(context.hash??'')}">${old?.feedback_context?.state==='changed'?notice(old.feedback_context.message,'warm'):''}${context.items?.length?`<section class="subpanel"><h4>本报告已有的解释复核 · ${context.items.length} 条</h4>${context.items.map((r:Json)=>`<p>${esc(({accepted:'人工接受',rejected:'人工拒绝',needs_evidence:'需要证据'} as Record<string,string>)[r.payload.verdict])}：${esc(r.payload.note)}</p>`).join('')}<p class="micro">你可以在知悉上述争议后授权本地能力回放；这不表示接受模型解释。复核内容变化后须重新确认。</p></section>`:''}${context.related_actions?.length?`<section class="subpanel"><h4>关联行动的实际处理反馈</h4>${context.related_actions.map((a:Json)=>`<article><strong>${esc(a.title)} · ${esc(({open:'待开展',in_progress:'进行中',blocked:'阻塞',done:'已验收',dismissed:'已搁置'} as Record<string,string>)[a.status]??a.status)}</strong><p class="micro">验收标准：${esc(a.acceptance)}</p><p>${esc(a.latest_record?.note??'尚未记录处理结果')}</p></article>`).join('')}<p class="micro">行动完成不证明经营改善或因果效果；授权只表示你已看到这次反馈。后续变更需重新确认。</p></section>`:''}${field('本次结果评价',select('verdict',{useful:'有用，已记录依据',needs_revision:'需要进一步修订',rejected:'不采用'},p.verdict??'needs_revision'))}${field('验收依据 / 未满足项',textarea('note',p.note??'','rows="4" required minlength="5" maxlength="2000"'))}<fieldset><legend>你原本期望的能力</legend><div class="capability-checks">${Object.entries({quality:'数据核验',quant:'量化计算',evidence:'证据检索',counterevidence:'反向对照',forecast:'预测回测',sensitivity:'情景计算',comparison:'企业对照',gaps:'缺口清单'}).map(([k,v])=>`<label class="check-label"><input type="checkbox" name="expected_capabilities" value="${k}" ${(p.expected_capabilities??[]).includes(k)?'checked':''}> ${v}</label>`).join('')}</div></fieldset><label class="check-label"><input type="checkbox" name="consent_replay" ${p.consent_replay&&old?.feedback_context?.state!=='changed'?'checked':''}> 允许使用本次冻结输入做本地策略回放，不调用外部模型</label>${notice('回放仅检验人工标注的能力覆盖与计算不变性，不代表模型事实准确率。可随时撤回后续回放授权。')}${formFooter('保存验收反馈')}</form>`;}
export async function evolutionPage(){
  const e=await workspace('/evolution');state.cache.evolution=e;const o=e.observations;
  return heading('策略实验室','从实际失败与人工验收中改进编排；先回放，再激活，随时回滚。',button('从验收生成并回放','strategy-propose','primary')+button('手动设定候选','strategy-dialog','secondary'))+
  `<section class="evolution-hero"><div><span class="eyebrow">当前规划策略</span><h2>${esc(e.active?.payload.spec?.name??'内置目标驱动策略')}</h2><p>只影响未来计划，不改写历史报告、数学公式或模型权重。</p>${e.active?.payload.history?.length?button('回滚到前一策略','strategy-rollback','secondary'):''}</div><div class="evolution-stats"><div><strong>${o.observed_runs}</strong><span>最近观察运行</span></div><div><strong>${o.consented_cases}</strong><span>明确授权案例</span></div><div><strong>${o.structural_rejections}</strong><span>输出门禁拦截</span></div></div></section><div class="two-columns"><section class="panel"><div class="section-heading"><h2>待比较的候选</h2></div>${e.candidates.length?e.candidates.map((c:Json)=>`<article class="strategy-card"><div class="row-between"><h3>${esc(c.payload.name)}</h3>${button('运行本地回放','strategy-evaluate','secondary',`data-id="${esc(c.id)}"`)}${button('清理候选','delete-strategy','text-button',`data-id="${esc(c.id)}" data-version="${c.version}"`)}</div><p>${esc(c.payload.note)}</p><div class="tag-row">${badge(({concise:'聚焦',balanced:'均衡',deep:'深入'} as Record<string,string>)[c.payload.depth])}${c.payload.require_counterevidence?badge('必须反向对照'):''}${c.payload.require_gap_analysis?badge('必须缺口规划'):''}</div></article>`).join(''):empty('尚无候选','先从报告记录验收依据，再建立有明确目的的策略候选。')}</section><section class="panel"><h2>回放结果与激活门槛</h2><p class="micro">展示全部保留记录（最多200份）。可清理未使用回放以释放容量；当前策略与回滚链受到保护。</p>${e.evaluations.length?e.evaluations.map((r:Json)=>`<article class="evaluation-card"><div class="row-between">${badge(r.payload.eligible?'本地门槛通过':'未达到激活门槛',r.payload.eligible?'good':'warm')}<small>${timeText(r.created_at)}</small></div><p>${r.payload.unique_inputs} 份不同输入 / ${r.payload.scenario_cases??r.payload.cases?.length??0} 个验收任务 · ${r.payload.improvements.length} 项改善 · ${r.payload.regressions.length} 项回归</p>${r.payload.blockers.map((b:string)=>`<p class="micro">${esc(b)}</p>`).join('')}<div class="inline-actions">${button('逐例对照','evaluation-detail','text-button',`data-id="${esc(r.id)}"`)}${button('清理回放','delete-evaluation','text-button',`data-id="${esc(r.id)}" data-version="${r.version}"`)}${r.payload.eligible?button('明确激活此策略','strategy-activate','secondary',`data-id="${esc(r.payload.candidate_id)}" data-evaluation="${esc(r.id)}"`):''}</div></article>`).join(''):empty('尚无回放','至少三份不同输入；重复运行不当作独立案例。')}</section></div><section class="panel"><h2>人工反馈与回放授权</h2>${e.assessments.length?e.assessments.map((a:Json)=>`<div class="row-between"><span>${esc(a.payload.note)}${a.feedback_context?.state==='changed'?notice(a.feedback_context.message,'warm'):''}</span>${routeButton('查看原报告与验收','agents:run-'+a.payload.run_id,'text-button')}</div>`).join(''):empty('尚无人工验收','从已完成报告记录预期能力与复核意见。')}</section><section class="panel"><h2>治理边界</h2><p>策略只改变注册能力的选择。任何新增外发、敏感记忆、模型调用仍受原有批准与预算约束。没有后台自主训练、写代码或扩大权限。</p>${notice('保留组按输入内容分组；本地门槛不是独立外部验证，也不是生产质量或模型事实正确性的证明。')}</section>`;
}
export function strategyForm(){return `<form id="strategy-form" class="stack">${field('候选名称',input('name','','required minlength="2" maxlength="80"'))}${field('默认研究深度',select('depth',{concise:'聚焦',balanced:'均衡',deep:'深入'},'balanced'))}<label class="check-label"><input type="checkbox" name="require_counterevidence"> 明确增加反向证据对照</label><label class="check-label"><input type="checkbox" name="require_gap_analysis"> 明确增加缺口补全规划</label>${field('改善假设与理由',textarea('note','','rows="4" required minlength="5" maxlength="1000"'))}${formFooter('保存候选，不自动激活')}</form>`;}

/** Separate HTTP reads can straddle an atomic server transition. Never strand a stale report. */
export function runNeedsReconcile(run:Json,runtime:Json){return !!runtime&&['succeeded','degraded','failed','cancelled','paused','interrupted'].includes(runtime.state)&&(run.state!==(runtime.run_state??runtime.state));}
